function showNetworkGraph() {
  var option = document.getElementById("cluster").value;
  
  const vypravec = '#c4688c',
  postava = '#78a8d1', // postava, se kterou vypravěč nebo jiná postava explicitně komunikuje
  postava2 = '#aeb6bf', // postava, se kterou vypravěč nebo jiná postava explicitně nekomunikuje, ale komunikace je vyprávěna (např. "promluvil jsem si s X")
  postava3 = '#f2d0a4'; // postava ve vloženém vyprávení
  
  const line = '#000000';
  const linewidth = 2.0;

  switch(option){
    case "svejk1":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Švejk (I. díl)'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Bretschneider", "Palivec"],
                    ["Palivec", "Bretschneider"],
                    ["Bretschneider", "Palivec"],
                    ["Palivec", "Bretschneider"],
                    ["Bretschneider", "Palivec"],
                    ["Palivec", "Bretschneider"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Palivec"],
                    ["Palivec", "Švejk"],
                    ["Bretschneider", "Palivec"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Palivec"],
                    ["Palivec", "Bretschneider"],
                    ["Švejk", "Palivec"],
                    ["Palivec", "Švejk"],
                    ["spoluvězni", "Švejk"],
                    ["Švejk", "spoluvězni"],
                    ["Švejk", "spoluvězni"],
                    ["spoluvězni", "Švejk"],
                    ["zježený muž", "Švejk"],
                    ["Švejk", "zježený muž"],
                    ["policejní rada", "Švejk"],
                    ["Švejk", "policejní rada"],
                    ["policejní rada", "Švejk"],
                    ["Švejk", "policejní rada"],
                    ["policejní rada", "Švejk"],
                    ["Švejk", "policejní rada"],
                    ["Palivec", "Švejk"],
                    ["Švejk", "Palivec"],
                    ["Palivec", "spoluvězni"],
                    ["policejní rada", "Švejk"],
                    ["Švejk", "policejní rada"],
                    ["soudní rada", "Švejk"],
                    ["Švejk", "soudní rada"],
                    ["soudní rada", "Švejk"],
                    ["Švejk", "soudní rada"],
                    ["soudní rada", "Švejk"],
                    ["Švejk", "soudní rada"],
                    ["spoluvězni", "Švejk"],
                    ["Švejk", "spoluvězni"],
                    ["spoluvězni", "Švejk"],
                    ["soudní lékaři", "Švejk"],
                    ["Švejk", "soudní lékaři"],
                    ["soudní lékaři", "Švejk"],
                    ["Švejk", "soudní lékaři"],
                    ["soudní lékaři", "Švejk"],
                    ["Švejk", "soudní lékaři"],
                    ["Švejk", "spoluvězni"],
                    ["spoluvězni", "Švejk"],
                    ["lékaři", "Švejk"],
                    ["Švejk", "lékaři"],
                    ["lékaři", "Švejk"],
                    ["Švejk", "lékaři"],
                    ["Švejk", "zadumaný muž"],
                    ["zadumaný muž", "Švejk"],
                    ["Švejk", "zadumaný muž"],
                    ["zadumaný muž", "Švejk"],
                    ["Švejk", "zadumaný muž"],
                    ["zadumaný muž", "Švejk"],
                    ["Švejk", "zadumaný muž"],
                    ["zadumaný muž", "Švejk"],
                    ["komisař", "Švejk"],
                    ["Švejk", "komisař"],
                    ["komisař", "Švejk"],
                    ["Švejk", "komisař"],
                    ["strážník", "Švejk"],
                    ["Švejk", "strážník"],
                    ["dravec", "Švejk"],
                    ["Švejk", "dravec"],
                    ["dravec", "Švejk"],
                    ["Švejk", "dravec"],
                    ["dravec", "Švejk"],
                    ["Švejk", "dravec"],
                    ["Švejk", "Palivcová"],
                    ["Palivcová", "Švejk"],
                    ["Švejk", "Palivcová"],
                    ["Palivcová", "Švejk"],
                    ["Švejk", "Palivcová"],
                    ["Palivcová", "Švejk"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Bretschneider", "Švejk"],
                    ["Švejk", "Bretschneider"],
                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Švejk", "Müllerová"],
                    ["Müllerová", "Švejk"],
                    ["Švejk", "Müllerová"],
                    ["Müllerová", "Švejk"],
                    ["Pávek", "Švejk"],
                    ["Švejk", "Pávek"],
                    ["Pávek", "Müllerová"],
                    ["Müllerová", "Pávek"],
                    ["Bautze", "Švejk"],
                    ["Švejk", "Bautze"],
                    ["Bautze", "šikovatel"],
                    ["šikovatel", "Bautze"],
                    ["marodi", "Švejk"],
                    ["Švejk", "marodi"],
                    ["marodi", "Švejk"],
                    ["Švejk", "marodi"],
                    ["marodi", "Švejk"],
                    ["Grünstein", "Švejk"],
                    ["Švejk", "Grünstein"],
                    ["Grünstein", "Švejk"],
                    ["Švejk", "Grünstein"],
                    ["Grünstein", "marodi"],
                    ["marodi", "Grünstein"],
                    ["baronka", "Švejk"],
                    ["Švejk", "baronka"],
                    ["baronka", "Grünstein"],
                    ["Grünstein", "baronka"],
                    ["Grünstein", "Švejk"],
                    ["Švejk", "Grünstein"],
                    ["komise", "Švejk"],
                    ["Švejk", "komise"],
                    ["komise", "Švejk"],
                    ["Švejk", "komise"],
                    ["Slavík", "Švejk"],
                    ["Švejk", "Slavík"],
                    ["Slavík", "Řepa"],
                    ["Řepa", "Slavík"],
                    ["Slavík", "Švejk"],
                    ["Švejk", "Slavík"],
                    ["cimrkomandant", "Švejk"],
                    ["Švejk", "cimrkomandant"],
                    ["Katz", "podvlíkačky"],
                    ["podvlíkačky", "Katz"],
                    ["Katz", "podvlíkačky"],
                    ["podvlíkačky", "Katz"],
                    ["Švejk", "soused"],
                    ["soused", "Švejk"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Katz", "Bernis"],
                    ["Bernis", "Katz"],
                    ["Katz", "Bernis"],
                    ["Bernis", "Katz"],
                    ["Bernis", "Linhart"],
                    ["Linhart", "Bernis"],
                    ["Bernis", "Švejk"],
                    ["Švejk", "Bernis"],
                    ["Bernis", "Švejk"],
                    ["Švejk", "Bernis"],
                    ["Bernis", "Slavík"],
                    ["Slavík", "Bernis"],
                    ["vězeň", "spoluvězni"],
                    ["spoluvězni", "vězeň"],
                    ["Švejk", "vězeň"],
                    ["vězeň", "Švejk"],
                    ["malý", "Švejk"],
                    ["Švejk", "malý"],
                    ["čahoun", "malý"],
                    ["malý", "čahoun"],
                    ["čahoun", "Švejk"],
                    ["Švejk", "čahoun"],
                    ["malý", "Švejk"],
                    ["Švejk", "malý"],
                    ["čahoun", "malý"],
                    ["malý", "čahoun"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Katz", "čahoun"],
                    ["čahoun", "Katz"],
                    ["Katz", "malý"],
                    ["sluha", "Švejk"],
                    ["Švejk", "sluha"],
                    ["Švejk", "Katz"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Katz", "Švejk"],
                    ["drožkář", "Švejk"],
                    ["Švejk", "drožkář"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Kejřová", "Švejk"],
                    ["Švejk", "Kejřová"],
                    ["Palivcová", "Švejk"],
                    ["Švejk", "Palivcová"],
                    ["zámečník", "Švejk"],
                    ["Švejk", "zámečník"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Švejk", "Kolařík"],
                    ["Kolařík", "Švejk"],
                    ["Katz", "Kolařík"],
                    ["Kolařík", "Katz"],
                    ["Katz", "farář"],
                    ["farář", "Katz"],
                    ["Švejk", "drožkář"],
                    ["drožkář", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Katz", "Švejk"],
                    ["katecheta", "Katz"],
                    ["Katz", "katecheta"],
                    ["katecheta", "Katz"],
                    ["Katz", "katecheta"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Švejk", "katecheta"],
                    ["katecheta", "Švejk"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["šéf", "příručí"],
                    ["příručí", "šéf"],
                    ["příručí", "Švejk"],
                    ["Švejk", "příručí"],
                    ["přísný pán", "Švejk"],
                    ["Švejk", "přísný pán"],
                    ["přísný pán", "Švejk"],
                    ["Švejk", "přísný pán"],
                    ["Katz", "věřitel"],
                    ["věřitel", "Katz"],
                    ["nezmar", "Katz"],
                    ["Katz", "nezmar"],
                    ["Švejk", "nezmar"],
                    ["nezmar", "Švejk"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["rezervista", "zeleňáček"],
                    ["zeleňáček", "rezervista"],
                    ["desátník", "Švejk"],
                    ["Švejk", "desátník"],
                    ["dáma", "Katz"],
                    ["Katz", "dáma"],
                    ["Katz", "Lukáš"],
                    ["Lukáš", "Katz"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Katz", "Švejk"],
                    ["Švejk", "Katz"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Katy", "Švejk"],
                    ["Švejk", "Katy"],
                    ["Katy", "Švejk"],
                    ["Švejk", "Katy"],
                    ["Lukáš", "poručík"],
                    ["poručík", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Švejk", "Katy"],
                    ["Katy", "Švejk"],
                    ["Wendler", "Lukáš"],
                    ["Lukáš", "Wendler"],
                    ["Wendler", "Lukáš"],
                    ["Lukáš", "Wendler"],
                    ["Wendler", "Katy"],
                    ["Katy", "Wendler"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Blahník", "Švejk"],
                    ["Švejk", "Blahník"],
                    ["Blahník", "Švejk"],
                    ["Švejk", "Blahník"],
                    ["Švejk", "služka"],
                    ["služka", "Švejk"],
                    ["Švejk", "služka"],
                    ["služka", "Švejk"],
                    ["Blahník", "Švejk"],
                    ["Švejk", "Blahník"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Kraus", "Lukáš"],
                    ["Lukáš", "Kraus"],
                    ["Kraus", "Lukáš"],
                    ["Lukáš", "Kraus"],
                    ["Švejk", "ordonanc"],
                    ["ordonanc", "Švejk"],
                    ["Švejk", "ordonanc"],
                    ["ordonanc", "Švejk"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Kraus", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    // postavy ve vypraveni Svejka (vnorene anekdoty):
                    ["Švejk", "vdova"], // (ve vypraveni Svejka - vdova po hajnem)
                    ["Švejk", "hejtman"], // (ve vypraveni Svejka - hejtman a zastreleny pes)
                    ["Švejk", "soustružník"], // (ve vypraveni Svejka - spi v kostele)
                    ["Švejk", "kostelník"], // (ve vypraveni Svejka)
                    ["Švejk", "vynálezce"], // (ve vypraveni Svejka - blazinec)
                    ["Švejk", "Vejvoda"], // (ve vypraveni Svejka - marias)
                    ["Švejk", "hospodský"], // (ve vypraveni Svejka - marias)
                    ["Švejk", "kominík"], // (ve vypraveni Svejka - marias)
                    ["Švejk", "dlaždič"], // (ve vypraveni Svejka - marias)
                    ["Švejk", "děkan"], // (ve vypraveni Svejka - sv. Augustin, protinozci)
                    ["Švejk", "posluhovačka"], // (ve vypraveni Svejka - dekanova posluhovacka)
                    ["Švejk", "šenkýř"], // (ve vypraveni Svejka - Malesice, Kdo setri metly)
                    ["Švejk", "Božetěch"], // (ve vypraveni Svejka - kradeni psu, Kosire)
                    ["Švejk", "paní s papouškem"], // (ve vypraveni Svejka - psi historky)
                    ["Švejk", "krejčí"], // (ve vypraveni Svejka - zlaty prsten)
                    ["Švejk", "poctivý nálezce"], // (ve vypraveni Svejka - vojak a 600 korun)
                    // postavy ve vypraveni vezne (cela c. 16):
                    ["vězeň", "fajnový host"], // (ve vypraveni vezne - fajnovy clovek, cela 16)
                    ["vězeň", "Libeňák"], // (ve vypraveni vezne - cela 16)

                    
                ], nodes: 

                    [

                    // hlavni postavy

                    {id: 'Švejk',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Lukáš',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Katz',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Müllerová',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Bretschneider',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Palivec',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejsi postavy

                    {id: 'spoluvězni',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'zježený muž',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'policejní rada',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'soudní rada',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'soudní lékaři',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'lékaři',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'zadumaný muž',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'komisař',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'strážník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'dravec',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Palivcová',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Pávek',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Bautze',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'šikovatel',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'marodi',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Grünstein',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'baronka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'komise',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Slavík',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Řepa',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'cimrkomandant',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'podvlíkačky',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'soused',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Bernis',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Linhart',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'vězeň',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'malý',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'čahoun',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'sluha',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'drožkář',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kejřová',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'zámečník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kolařík',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'farář',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'katecheta',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'šéf',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'příručí',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'přísný pán',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'věřitel',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'nezmar',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'rezervista',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'zeleňáček',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'desátník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'dáma',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Katy',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'poručík',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Wendler',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Blahník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'služka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kraus',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'ordonanc',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    // postavy ve vnorenych anekdotach (ve vypraveni postav)

                    {id: 'vdova',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'hejtman',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'soustružník',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'kostelník',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'vynálezce',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Vejvoda',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'hospodský',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'kominík',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'dlaždič',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'děkan',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'posluhovačka',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'šenkýř',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Božetěch',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'paní s papouškem',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'krejčí',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'poctivý nálezce',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'fajnový host',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Libeňák',marker: {radius: 5, lineWidth: linewidth, lineColor: line}, color: postava3},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters, <span style="color:' + postava3 + '">&#9679;</span> characters in embedded anecdotes';
      break;
    case "svejk2":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Švejk (II. díl)'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Schwarzburg", "Lukáš"],
                    ["Lukáš", "Schwarzburg"],
                    ["Schwarzburg", "Lukáš"],
                    ["Lukáš", "Schwarzburg"],
                    ["Schwarzburg", "Lukáš"],
                    ["Lukáš", "Schwarzburg"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "železniční zřízenec"],
                    ["železniční zřízenec", "Švejk"],
                    ["Švejk", "železniční zřízenec"],
                    ["železniční zřízenec", "Švejk"],
                    ["Švejk", "železniční zřízenec"],
                    ["železniční zřízenec", "Švejk"],
                    ["Švejk", "průvodčí"],
                    ["průvodčí", "Švejk"],
                    ["Švejk", "průvodčí"],
                    ["průvodčí", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "přednosta"],
                    ["přednosta", "Švejk"],
                    ["Švejk", "dobrodinec"],
                    ["dobrodinec", "Švejk"],
                    ["Švejk", "dobrodinec"],
                    ["dobrodinec", "Švejk"],
                    ["Švejk", "Maďar"],
                    ["Maďar", "Švejk"],
                    ["Švejk", "Maďar"],
                    ["Maďar", "Švejk"],
                    ["Švejk", "Maďar"],
                    ["Maďar", "Švejk"],
                    ["Švejk", "šikovatel"],
                    ["šikovatel", "Švejk"],
                    ["Švejk", "šikovatel"],
                    ["šikovatel", "Švejk"],
                    ["šikovatel", "landverák"],
                    ["landverák", "šikovatel"],
                    ["Švejk", "landverák"],
                    ["landverák", "Švejk"],
                    ["Švejk", "landverák"],
                    ["landverák", "Švejk"],
                    ["Švejk", "poručík"],
                    ["poručík", "Švejk"],
                    ["Švejk", "poručík"],
                    ["poručík", "Švejk"],
                    ["Švejk", "poručík"],
                    ["poručík", "Švejk"],
                    ["Švejk", "poručík"],
                    ["poručík", "Švejk"],
                    ["poručík", "Palánek"],
                    ["Palánek", "poručík"],
                    ["Švejk", "Palánek"],
                    ["Palánek", "Švejk"],
                    ["Švejk", "Palánek"],
                    ["Palánek", "Švejk"],
                    ["Švejk", "babička"],
                    ["babička", "Švejk"],
                    ["Švejk", "babička"],
                    ["babička", "Švejk"],
                    ["Švejk", "babička"],
                    ["babička", "Švejk"],
                    ["Švejk", "harmonikář"],
                    ["harmonikář", "Švejk"],
                    ["Švejk", "harmonikář"],
                    ["harmonikář", "Švejk"],
                    ["Švejk", "Melichárek"],
                    ["Melichárek", "Švejk"],
                    ["Švejk", "Melichárek"],
                    ["Melichárek", "Švejk"],
                    ["Švejk", "vandrák"],
                    ["vandrák", "Švejk"],
                    ["Švejk", "vandrák"],
                    ["vandrák", "Švejk"],
                    ["Švejk", "vandrák"],
                    ["vandrák", "Švejk"],
                    ["Švejk", "vandrák"],
                    ["vandrák", "Švejk"],
                    ["vandrák", "ovčák"],
                    ["ovčák", "vandrák"],
                    ["vandrák", "ovčák"],
                    ["ovčák", "vandrák"],
                    ["Švejk", "ovčák"],
                    ["ovčák", "Švejk"],
                    ["Švejk", "ovčák"],
                    ["ovčák", "Švejk"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Flanderka", "závodčí"],
                    ["závodčí", "Flanderka"],
                    ["Flanderka", "závodčí"],
                    ["závodčí", "Flanderka"],
                    ["Flanderka", "závodčí"],
                    ["závodčí", "Flanderka"],
                    ["Flanderka", "závodčí"],
                    ["závodčí", "Flanderka"],
                    ["Flanderka", "závodčí"],
                    ["závodčí", "Flanderka"],
                    ["Flanderka", "Pepek"],
                    ["Pepek", "Flanderka"],
                    ["Flanderka", "Pepek"],
                    ["Pepek", "Flanderka"],
                    ["Flanderka", "farář"],
                    ["farář", "Flanderka"],
                    ["Flanderka", "Pejzlerka"],
                    ["Pejzlerka", "Flanderka"],
                    ["Flanderka", "Pejzlerka"],
                    ["Pejzlerka", "Flanderka"],
                    ["Flanderka", "Pejzlerka"],
                    ["Pejzlerka", "Flanderka"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Švejk", "Flanderka"],
                    ["Flanderka", "Švejk"],
                    ["Švejk", "závodčí"],
                    ["závodčí", "Švejk"],
                    ["Švejk", "závodčí"],
                    ["závodčí", "Švejk"],
                    ["Švejk", "závodčí"],
                    ["závodčí", "Švejk"],
                    ["Švejk", "závodčí"],
                    ["závodčí", "Švejk"],
                    ["závodčí", "hostinský"],
                    ["hostinský", "závodčí"],
                    ["König", "závodčí"],
                    ["závodčí", "König"],
                    ["König", "závodčí"],
                    ["závodčí", "König"],
                    ["König", "Matějka"],
                    ["Matějka", "König"],
                    ["König", "Matějka"],
                    ["Matějka", "König"],
                    ["König", "Švejk"],
                    ["Švejk", "König"],
                    ["König", "Švejk"],
                    ["Švejk", "König"],
                    ["König", "Švejk"],
                    ["Švejk", "König"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Marek", "profous"],
                    ["profous", "Marek"],
                    ["Marek", "profous"],
                    ["profous", "Marek"],
                    ["Marek", "profous"],
                    ["profous", "Marek"],
                    ["Marek", "Pelikán"],
                    ["Pelikán", "Marek"],
                    ["Marek", "Pelikán"],
                    ["Pelikán", "Marek"],
                    ["Schröder", "Marek"],
                    ["Marek", "Schröder"],
                    ["Schröder", "Marek"],
                    ["Marek", "Schröder"],
                    ["Schröder", "Marek"],
                    ["Marek", "Schröder"],
                    ["Schröder", "Marek"],
                    ["Marek", "Schröder"],
                    ["Schröder", "Švejk"],
                    ["Švejk", "Schröder"],
                    ["Schröder", "Švejk"],
                    ["Švejk", "Schröder"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Schröder", "Ságner"],
                    ["Ságner", "Schröder"],
                    ["Schröder", "Ságner"],
                    ["Ságner", "Schröder"],
                    ["Schröder", "Ságner"],
                    ["Ságner", "Schröder"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "desátník"],
                    ["desátník", "Švejk"],
                    ["Švejk", "desátník"],
                    ["desátník", "Švejk"],
                    ["Švejk", "desátník"],
                    ["desátník", "Švejk"],
                    ["Švejk", "desátník"],
                    ["desátník", "Švejk"],
                    ["Švejk", "desátník"],
                    ["desátník", "Švejk"],
                    ["Švejk", "desátník"],
                    ["desátník", "Švejk"],
                    ["Marek", "desátník"],
                    ["desátník", "Marek"],
                    ["Marek", "desátník"],
                    ["desátník", "Marek"],
                    ["Marek", "desátník"],
                    ["desátník", "Marek"],
                    ["Marek", "desátník"],
                    ["desátník", "Marek"],
                    ["Marek", "desátník"],
                    ["desátník", "Marek"],
                    ["Lacina", "Švejk"],
                    ["Švejk", "Lacina"],
                    ["Lacina", "Švejk"],
                    ["Švejk", "Lacina"],
                    ["Lacina", "Švejk"],
                    ["Švejk", "Lacina"],
                    ["Lacina", "desátník"],
                    ["desátník", "Lacina"],
                    ["Lacina", "desátník"],
                    ["desátník", "Lacina"],
                    ["Lacina", "desátník"],
                    ["desátník", "Lacina"],
                    ["Lacina", "Marek"],
                    ["Marek", "Lacina"],
                    ["Lacina", "Marek"],
                    ["Marek", "Lacina"],
                    ["Švejk", "eskorta"],
                    ["eskorta", "Švejk"],
                    ["Švejk", "eskorta"],
                    ["eskorta", "Švejk"],
                    ["Švejk", "eskorta"],
                    ["eskorta", "Švejk"],
                    ["Marek", "eskorta"],
                    ["eskorta", "Marek"],
                    ["Mráz", "desátník"],
                    ["desátník", "Mráz"],
                    ["Mráz", "desátník"],
                    ["desátník", "Mráz"],
                    ["Mráz", "Švejk"],
                    ["Švejk", "Mráz"],
                    ["Mráz", "Švejk"],
                    ["Švejk", "Mráz"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Mikulášek"],
                    ["Mikulášek", "Švejk"],
                    ["Švejk", "Mikulášek"],
                    ["Mikulášek", "Švejk"],
                    ["Švejk", "Mikulášek"],
                    ["Mikulášek", "Švejk"],
                    ["Lukáš", "Mikulášek"],
                    ["Mikulášek", "Lukáš"],
                    ["Lukáš", "Mikulášek"],
                    ["Mikulášek", "Lukáš"],
                    ["Lukáš", "Kákonyiová"],
                    ["Kákonyiová", "Lukáš"],
                    ["Lukáš", "Kákonyiová"],
                    ["Kákonyiová", "Lukáš"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "služka"],
                    ["služka", "Švejk"],
                    ["Švejk", "služka"],
                    ["služka", "Švejk"],
                    ["Vodička", "Kákonyi"],
                    ["Kákonyi", "Vodička"],
                    ["Vodička", "Kákonyi"],
                    ["Kákonyi", "Vodička"],
                    ["Vodička", "Kákonyi"],
                    ["Kákonyi", "Vodička"],
                    ["Švejk", "Kákonyi"],
                    ["Kákonyi", "Švejk"],
                    ["Švejk", "Kákonyi"],
                    ["Kákonyi", "Švejk"],
                    ["Švejk", "Kákonyiová"],
                    ["Kákonyiová", "Švejk"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Schröder", "Lukáš"],
                    ["Lukáš", "Schröder"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "vězeň"],
                    ["vězeň", "Švejk"],
                    ["Švejk", "vězeň"],
                    ["vězeň", "Švejk"],
                    ["Švejk", "učitel"],
                    ["učitel", "Švejk"],
                    ["Švejk", "učitel"],
                    ["učitel", "Švejk"],
                    ["Švejk", "učitel"],
                    ["učitel", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Švejk", "Marek"],
                    ["Marek", "Švejk"],
                    ["Ruller", "Švejk"],
                    ["Švejk", "Ruller"],
                    ["Ruller", "Švejk"],
                    ["Švejk", "Ruller"],
                    ["Ruller", "Švejk"],
                    ["Švejk", "Ruller"],
                    ["Ruller", "Vodička"],
                    ["Vodička", "Ruller"],
                    ["Ruller", "Vodička"],
                    ["Vodička", "Ruller"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Švejk", "Vodička"],
                    ["Vodička", "Švejk"],
                    ["Lukáš", "Vaněk"],
                    ["Vaněk", "Lukáš"],
                    ["Lukáš", "Vaněk"],
                    ["Vaněk", "Lukáš"],
                    ["Lukáš", "Vaněk"],
                    ["Vaněk", "Lukáš"],
                    ["Lukáš", "Vaněk"],
                    ["Vaněk", "Lukáš"],
                    ["Lukáš", "Vaněk"],
                    ["Vaněk", "Lukáš"],
                    ["Lukáš", "Vaněk"],
                    ["Vaněk", "Lukáš"],
                    ["Lukáš", "Baloun"],
                    ["Baloun", "Lukáš"],
                    ["Lukáš", "Baloun"],
                    ["Baloun", "Lukáš"],
                    ["Lukáš", "Baloun"],
                    ["Baloun", "Lukáš"],
                    ["Lukáš", "Baloun"],
                    ["Baloun", "Lukáš"],
                    ["Vaněk", "Baloun"],
                    ["Baloun", "Vaněk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Lukáš"],
                    ["Lukáš", "Švejk"],
                    ["Švejk", "Braun"],
                    ["Braun", "Švejk"],
                    ["Švejk", "Braun"],
                    ["Braun", "Švejk"],
                    ["Švejk", "Braun"],
                    ["Braun", "Švejk"],
                    ["Švejk", "Fuchs"],
                    ["Fuchs", "Švejk"],
                    ["Švejk", "Fuchs"],
                    ["Fuchs", "Švejk"],
                    ["Švejk", "Fuchs"],
                    ["Fuchs", "Švejk"],
                    ["Švejk", "Baloun"],
                    ["Baloun", "Švejk"],
                    ["Švejk", "Baloun"],
                    ["Baloun", "Švejk"],
                    ["Vaněk", "štábní šikovatel"],
                    ["štábní šikovatel", "Vaněk"],
                    ["Vaněk", "štábní šikovatel"],
                    ["štábní šikovatel", "Vaněk"],
                    ["Vaněk", "Jurajda"],
                    ["Jurajda", "Vaněk"],
                    ["Vaněk", "Jurajda"],
                    ["Jurajda", "Vaněk"],
                    ["Vaněk", "Jurajda"],
                    ["Jurajda", "Vaněk"],
                    ["Schröder", "Ságner"],
                    ["Ságner", "Schröder"],
                    ["Schröder", "Ságner"],
                    ["Ságner", "Schröder"],
                    ["Vaněk", "Biegler"],
                    ["Biegler", "Vaněk"],
                    ["Vaněk", "Biegler"],
                    ["Biegler", "Vaněk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Švejk", "Vaněk"],
                    ["Vaněk", "Švejk"],
                    ["Hývl", "Rous"],
                    ["Rous", "Hývl"],
                    ["Hývl", "Rous"],
                    ["Rous", "Hývl"],
                    ["Paroubek", "dráteník"],
                    ["dráteník", "Paroubek"],
                    ["Paroubek", "dráteník"],
                    ["dráteník", "Paroubek"],
                    ["Moc", "Pech"],
                    ["Pech", "Moc"],
                    ["Moc", "Pech"],
                    ["Pech", "Moc"],
                    ["Blüher", "rekrut"],
                    ["rekrut", "Blüher"],
                    ["Blüher", "rekrut"],
                    ["rekrut", "Blüher"],

                    // spojnice na vypravece anekdot (jednosmerne)
                    ["Švejk", "Hývl"], // (ve vypraveni Svejka - sunka ve vlaku, Leoben)
                    ["Švejk", "Paroubek"], // (ve vypraveni Svejka - koralecnik v Libni)
                    ["Švejk", "Moc"], // (ve vypraveni Svejka - rekrut Pech, vyrocni trhy)
                    ["Švejk", "Blüher"], // (ve vypraveni Svejka - major a vojenska vrchnost)

                ], nodes:

                    [

                    // hlavni postavy

                    {id: 'Švejk',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Lukáš',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Marek',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Vodička',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Flanderka',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Schröder',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Vaněk',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Baloun',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejsi postavy

                    {id: 'Schwarzburg',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'železniční zřízenec',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'průvodčí',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'přednosta',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'dobrodinec',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Maďar',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'šikovatel',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'landverák',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'poručík',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Palánek',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'babička',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'harmonikář',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Melichárek',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'vandrák',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'ovčák',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'závodčí',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Pepek',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'farář',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Pejzlerka',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'hostinský',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'König',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Matějka',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'profous',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Pelikán',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Ságner',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'desátník',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Lacina',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'eskorta',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Mráz',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Mikulášek',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kákonyiová',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'služka',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kákonyi',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'vězeň',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'učitel',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Ruller',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Braun',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Fuchs',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'štábní šikovatel',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Jurajda',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Biegler',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},

                    // postavy ve vnorenych anekdotach (ve vypraveni postav)

                    {id: 'Hývl',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Rous',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Paroubek',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'dráteník',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Moc',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Pech',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'Blüher',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},
                    {id: 'rekrut',marker: {radius: 5,lineWidth: linewidth, lineColor: line}, color: postava3},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
    default:
    document.getElementById("container-person").src = "";   
  }
}
