function showGIS() {
    var cluster = document.getElementById("gis-cluster").value;

    switch (cluster) {
        case "flvek1":
            Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.42115, 50.0865], zoom: 7}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: ''}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
            {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
                {name: 'Dobruška (rodiště F. L. Věka)', lon: 16.1597, lat: 50.2925, image: "../foto_praha/dobruska.jpg"},
                {name: 'Hradec Králové', lon: 15.8328, lat: 50.2092, image: "../foto_praha/hradec_kralove.jpeg"},
                {name: 'Roudnice nad Labem (zámek knížete z Lobkovic)', lon: 14.2611, lat: 50.4258, image: "../foto_praha/roudnice_nad_labem.jpg"},
                {name: 'Kralíky', lon: 16.7619, lat: 50.0856, image: "../foto_praha/kraliky.jpg"},
                {name: 'Pražský hrad / Hradčany (chrám sv. Víta)', lon: 14.4001, lat: 50.0905, image: "../foto_praha/hradcany.jpg"},
                {name: 'Klementinum, Staré Město', lon: 14.4158, lat: 50.0865, image: "../foto_praha/storzer_klementinum.JPG"},
                {name: 'Staré Město pražské', lon: 14.421, lat: 50.0875, image: "../foto_praha/staremesto.jpg"},
                {name: 'Staroměstské náměstí', lon: 14.4213, lat: 50.0875, image: "../foto_praha/staromestskenamesti.jpg"},
                {name: 'Nové Město pražské', lon: 14.427, lat: 50.078, image: "../foto_praha/novemesto.jpg"},
                {name: 'Řeznická ulice, Nové Město', lon: 14.4205, lat: 50.0786, image: "../foto_praha/reznicka_ulice_nove_mesto.jpg"},
                {name: 'Koňský trh (dnes Václavské náměstí)', lon: 14.4275, lat: 50.081, image: "../foto_praha/Storzer_vaclavak.jpg"},
                {name: 'Karlův most', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluvmost.jpg"},
                {name: 'Bertramka (usedlost Dušků), Smíchov', lon: 14.3956, lat: 50.0719, image: "../foto_praha/bertramka.jpg"},
                {name: 'Pohořelec, Hradčany', lon: 14.3915, lat: 50.0879, image: "../foto_praha/pohorelec.jpg"},
                {name: 'Stavovské (Nosticovo) divadlo, Ovocný trh', lon: 14.4234, lat: 50.0863, image: "../foto_praha/nosticuvpalac.jpg"},
            ]},
            {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
                {name: 'Vlastenecká Bouda (1786–1789), Koňský trh', lon: 14.4275, lat: 50.0815, image: "../foto_praha/vlastenecka_bouda.jpeg"},
            ]},]});
            break;
        case "flvek2":
            Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.4205, 50.0858], zoom: 6}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: ''}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
            {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
                {name: 'Dobytčí trh (dnes Karlovo náměstí), Praha', lon: 14.4205, lat: 50.0758, image: "../foto_praha/zmelik_dobytcitrh.jpg"},
                {name: 'Kostel sv. Ignáce, Karlovo náměstí, Praha', lon: 14.4212, lat: 50.076, image: "../foto_praha/kostel_sv_ignace_karlovo_namesti_praha.jpeg"},
                {name: 'Staroměstské náměstí, Praha', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestskenamesti.jpg"},
                {name: 'Malé náměstí, Staré Město, Praha', lon: 14.4195, lat: 50.0865, image: "../foto_praha/male_namesti.jpg"},
                {name: 'Karlův (Kamenný) most, Praha', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluvmost.jpg"},
                {name: 'Pražský hrad, Praha', lon: 14.4001, lat: 50.0905, image: "../foto_praha/hradcany.jpg"},
                {name: 'Hradčanské náměstí, Praha', lon: 14.3985, lat: 50.089, image: "../foto_praha/storzer_hradcanske_n.jpg"},
                {name: 'Malá Strana, Praha', lon: 14.404, lat: 50.0884, image: "../foto_praha/malastrana.jpg"},
                {name: 'Staré Město, Praha', lon: 14.421, lat: 50.0875, image: "../foto_praha/staremesto.jpg"},
                {name: 'Nové Město, Praha', lon: 14.427, lat: 50.078, image: "../foto_praha/novemesto.jpg"},
                {name: 'Strahovský klášter, Praha', lon: 14.3885, lat: 50.0855, image: "../foto_praha/strahovsky_klaster.jpg"},
                {name: 'Emauzský klášter, Praha', lon: 14.4175, lat: 50.0719, image: "../foto_praha/storzer_emauzy.png"},
                {name: 'Hybernský klášter, Praha', lon: 14.4285, lat: 50.0888, image: "../foto_praha/hybernsky_klaster.jpg"},
                {name: 'Křížovnický kostel sv. Františka, Praha', lon: 14.4135, lat: 50.086, image: "../foto_praha/krizovnicky_kostel_sv_frantiska_praha.jpg"},
                {name: 'Petřín, Praha', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin.jpg"},
                {name: 'Prašná brána, Praha', lon: 14.428, lat: 50.0875, image: "../foto_praha/storzer_prasnab.jpg"},
                {name: 'Celetná ulice, Praha', lon: 14.4242, lat: 50.0873, image: "../foto_praha/zmelik_celetna.jpg"},
                {name: 'Železná ulice, Praha', lon: 14.422, lat: 50.0858, image: "../foto_praha/zelezna_ulice.jpg"},
                {name: 'Jilská ulice, Praha', lon: 14.4185, lat: 50.085, image: "../foto_praha/jilska_ulice_praha.jpg"},
                {name: 'Michalská ulice, Praha', lon: 14.419, lat: 50.0855, image: "../foto_praha/storzer_michalska.jpg"},
                {name: 'Spálená ulice, Praha', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice.jpeg"},
                {name: 'Ječná ulice, Praha', lon: 14.4235, lat: 50.0745, image: "../foto_praha/jecna_svejk.jpg"},
                {name: 'Vodičkova ulice, Praha', lon: 14.423, lat: 50.079, image: "../foto_praha/vodickova_svejk.jpg"},
                {name: 'Panská ulice, Praha', lon: 14.427, lat: 50.0838, image: "../foto_praha/panska_svejk.jpg"},
                {name: 'Řeznická ulice, Praha', lon: 14.4205, lat: 50.0775, image: "../foto_praha/reznicka.jpeg"},
                {name: 'Lipová ulice, Praha', lon: 14.4215, lat: 50.0745, image: "../foto_praha/storzer_lipova.png"},
                {name: 'Řetězová ulice, Praha', lon: 14.417, lat: 50.0858, image: "../foto_praha/retezova_ulice_praha.jpg"},
                {name: 'Poštovská ulice (dnes Karoliny Světlé), Praha', lon: 14.4145, lat: 50.0848, image: "../foto_praha/postovska_ulice.jpg"},
                {name: 'Vltava, Praha', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava.jpg"},
                {name: 'Dobruška', lon: 16.1611, lat: 50.2922, image: "../foto_praha/dobruska.jpg"},
                {name: 'Opočno', lon: 16.1147, lat: 50.2697, image: "../foto_praha/opocno.jpg"},
                {name: 'Kralíky', lon: 16.7592, lat: 50.0853, image: "../foto_praha/kraliky.jpg"},
                {name: 'Náchod', lon: 16.1656, lat: 50.4156, image: "../foto_praha/storzer_nachod.jpg"},
                {name: 'Rychnov nad Kněžnou', lon: 16.275, lat: 50.1631, image: "../foto_praha/rychnov_nad_kneznou.png"},
                {name: 'Jaroměř', lon: 15.9214, lat: 50.3556, image: "../foto_praha/storzer_jaromer.jpg"},
                {name: 'Orlické hory', lon: 16.45, lat: 50.2333, image: "../foto_praha/orlicke_hory.jpg"},
                {name: 'Poděbrady', lon: 15.1189, lat: 50.1425, image: "../foto_praha/podebrady.jpg"},
                {name: 'Český Brod', lon: 14.8606, lat: 50.0742, image: "../foto_praha/cesky_brod.jpg"},
                {name: 'Vídeň', lon: 16.3738, lat: 48.2082, image: "../foto_praha/zmelik_viden.jpg"},
            ]},
            {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
                {name: 'Chrám Božího těla (zbořen 1791), Karlovo náměstí, Praha', lon: 14.42, lat: 50.0765, image: "../foto_praha/chram_boziho_tela.jpg"},
                {name: 'Poříčská brána (zbořena), Praha', lon: 14.431, lat: 50.09, image: "../foto_praha/storzer_poricskab.jpg"},
                {name: 'Špitálská brána (zbořena), Praha', lon: 14.4292, lat: 50.0895, image: "../foto_praha/spitalska_brana.jpg"},
            ]},]});
            break;
        case "flvek3":
            Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.421, 50.087], zoom: 6}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: ''}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
            {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
                {name: 'Hradčany', lon: 14.399, lat: 50.0894, image: "../foto_praha/hradcany.jpg"},
                {name: 'Malá Strana', lon: 14.404, lat: 50.0884, image: "../foto_praha/malastrana.jpg"},
                {name: 'Staré Město', lon: 14.421, lat: 50.0875, image: "../foto_praha/staremesto.jpg"},
                {name: 'Nové Město', lon: 14.427, lat: 50.078, image: "../foto_praha/novemesto.jpg"},
                {name: 'Josefov', lon: 14.418, lat: 50.09, image: "../foto_praha/josefov.jpg"},
                {name: 'Vltava', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava.jpg"},
                {name: 'Karlův most', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluvmost.jpg"},
                {name: 'Kampa', lon: 14.4075, lat: 50.0858, image: "../foto_praha/kampa.jpg"},
                {name: 'Petřín', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin.jpg"},
                {name: 'Letná', lon: 14.417, lat: 50.0975, image: "../foto_praha/storzer_letna.jpg"},
                {name: 'Žižkov', lon: 14.449, lat: 50.087, image: "../foto_praha/zizkov_svejk.jpg"},
                {name: 'Libeň', lon: 14.469, lat: 50.108, image: "../foto_praha/liben_svejk.jpg"},
                {name: 'Podskalí', lon: 14.415, lat: 50.066, image: "../foto_praha/zmelik_podskali.jpg"},
                {name: 'Staroměstské náměstí', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestskenamesti.jpg"},
                {name: 'Koňský trh (dnes Václavské náměstí)', lon: 14.427, lat: 50.081, image: "../foto_praha/Storzer_vaclavak.jpg"},
                {name: 'Dobytčí trh (dnes Karlovo náměstí)', lon: 14.4205, lat: 50.0758, image: "../foto_praha/karlovonamesti_svejk.jpg"},
                {name: 'Ostruhová ulice (dnes Nerudova)', lon: 14.4007, lat: 50.0883, image: "../foto_praha/ostruhova.jpg"},
                {name: 'Spálená ulice', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice.jpeg"},
                {name: 'Ječná ulice', lon: 14.422, lat: 50.0758, image: "../foto_praha/jecna_svejk.jpg"},
                {name: 'Mostecká ulice', lon: 14.406, lat: 50.0878, image: "../foto_praha/mosteckaulice.jpg"},
                {name: 'Vodičkova ulice', lon: 14.4232, lat: 50.0808, image: "../foto_praha/vodickova_svejk.jpg"},
                {name: 'Dominikánská ulice (dnes Husova)', lon: 14.4185, lat: 50.0865, image: "../foto_praha/dominikanska.jpg"},
                {name: 'Jezuitská ulice (dnes Karlova)', lon: 14.4165, lat: 50.0865, image: "../foto_praha/karlovaulice.jpg"},
                {name: 'Prašná brána', lon: 14.4281, lat: 50.0875, image: "../foto_praha/storzer_prasnab.jpg"},
                {name: 'Stavovské divadlo', lon: 14.4233, lat: 50.0866, image: "../foto_praha/nosticuvpalac.jpg"},
                {name: 'Klášter Hybernů (U Hybernů)', lon: 14.4286, lat: 50.0889, image: "../foto_praha/hybernsky_klaster.jpg"},
                {name: 'Špitál Milosrdných bratří (Na Františku)', lon: 14.4188, lat: 50.0908, image: "../foto_praha/milosrdni.jpg"},
                {name: 'Novoměstská radnice', lon: 14.4205, lat: 50.0784, image: "../foto_praha/novomestska_radnice.jpg"},
                {name: 'Kanálská zahrada', lon: 14.435, lat: 50.0742, image: "../foto_praha/storzer_kanalka.jpg"},
                {name: 'Olšanské hřbitovy', lon: 14.472, lat: 50.082, image: "../foto_praha/zmelik_olsany.jpg"},
                {name: 'Dobruška', lon: 16.1606, lat: 50.2906, image: "../foto_praha/dobruska.jpg"},
                {name: 'Opočno', lon: 16.1147, lat: 50.27, image: "../foto_praha/opocno.jpg"},
                {name: 'Třebechovice pod Orebem', lon: 16.0103, lat: 50.203, image: "../foto_praha/trebechovice.jpg"},
                {name: 'Hradec Králové', lon: 15.8328, lat: 50.2092, image: "../foto_praha/hradec_kralove.jpeg"},
                {name: 'Český Brod', lon: 14.8607, lat: 50.0744, image: "../foto_praha/cesky_brod.jpg"},
                {name: 'Teplice', lon: 13.8245, lat: 50.6404, image: "../foto_praha/teplice.jpg"},
                {name: 'Karlovy Vary', lon: 12.8711, lat: 50.2329, image: "../foto_praha/karlovy_vary.jpg"},
                {name: 'Vídeň', lon: 16.3738, lat: 48.2082, image: "../foto_praha/zmelik_viden.jpg"},
            ]},
            {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
                {name: 'Koňská brána (zbořena 1875)', lon: 14.429, lat: 50.0815, image: "../foto_praha/storzer_konska_brana.jpg"},
                {name: 'Poříčská brána (zbořena 1874)', lon: 14.4322, lat: 50.0908, image: "../foto_praha/storzer_poricskab.png"},
            ]},]});
            break;
        case "flvek4":
            Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.418, 50.086], zoom: 5}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: ''}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
            {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
                {name: 'Hradčany', lon: 14.399, lat: 50.0894, image: "../foto_praha/hradcany.jpg"},
                {name: 'Malá Strana', lon: 14.404, lat: 50.0884, image: "../foto_praha/malastrana.jpg"},
                {name: 'Staré Město', lon: 14.421, lat: 50.0875, image: "../foto_praha/staremesto.jpg"},
                {name: 'Nové Město', lon: 14.427, lat: 50.078, image: "../foto_praha/novemesto.jpg"},
                {name: 'Josefov', lon: 14.418, lat: 50.09, image: "../foto_praha/storzer_josefov.jpg"},
                {name: 'Vyšehrad', lon: 14.4176, lat: 50.0641, image: "../foto_praha/vysehrad.jpg"},
                {name: 'Strahov', lon: 14.3895, lat: 50.0855, image: "../foto_praha/strahov.jpg"},
                {name: 'Vltava', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava.jpg"},
                {name: 'Karlův most', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluvmost.jpg"},
                {name: 'Staroměstské náměstí', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestskenamesti.jpg"},
                {name: 'Spálená ulice', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice.jpg"},
                {name: 'Ječná ulice', lon: 14.4235, lat: 50.0758, image: "../foto_praha/jecna_svejk.jpg"},
                {name: 'Dominikánská ulice (dnes Husova), Praha', lon: 14.4178, lat: 50.0863, image: "../foto_praha/dominikanska.jpg"},
                {name: 'Bartolomějská ulice', lon: 14.4178, lat: 50.0843, image: "../foto_praha/bartolomejska.jpg"},
                {name: 'Široká ulice, Praha', lon: 14.4185, lat: 50.0896, image: "../foto_praha/karlovonamesti_svejk.jpg"},
                {name: 'Sirková ulice, Praha', lon: 14.418, lat: 50.0905, image: "../foto_praha/sirkova_ulice_praha.jpg"},
                {name: 'Stavovské divadlo', lon: 14.4234, lat: 50.0838, image: "../foto_praha/stavovske_divadlo.jpg"},
                {name: 'Koňský trh (dnes Václavské náměstí)', lon: 14.427, lat: 50.081, image: "../foto_praha/Storzer_vaclavak.jpg"},
                {name: 'Dobytčí trh (dnes Karlovo náměstí)', lon: 14.4205, lat: 50.0758, image: "../foto_praha/zmelik_dobytcitrh.jpg"},
                {name: 'Dobruška', lon: 16.1597, lat: 50.2906, image: "../foto_praha/dobruska.jpg"},
                {name: 'Opočno', lon: 16.1147, lat: 50.2683, image: "../foto_praha/opocno.jpg"},
                {name: 'Solnice', lon: 16.2389, lat: 50.2056, image: "../foto_praha/solnice.jpg"},
                {name: 'Hradec Králové', lon: 15.8328, lat: 50.2092, image: "../foto_praha/hradec_kralove.jpeg"},
                {name: 'Litomyšl', lon: 16.3108, lat: 49.8722, image: "../foto_praha/litomysl.jpg"},
                {name: 'Vysoké Mýto', lon: 16.1611, lat: 49.9531, image: "../foto_praha/vysoke_myto.jpg"},
                {name: 'Chrudim', lon: 15.7956, lat: 49.9511, image: "../foto_praha/storzer_chrudim.jpg"},
                {name: 'Roudnice nad Labem', lon: 14.2611, lat: 50.4254, image: "../foto_praha/roudnice_nad_labem.jpg"},
                {name: 'Tábor', lon: 14.6578, lat: 49.4144, image: "../foto_praha/storzer_tabor.jpg"},
                {name: 'Plzeň', lon: 13.3776, lat: 49.7475, image: "../foto_praha/Storzer_plzen.jpg"},
                {name: 'Domažlice', lon: 12.93, lat: 49.4406, image: "../foto_praha/Storzer_domazlice.jpg"},
                {name: 'Klatovy', lon: 13.295, lat: 49.3954, image: "../foto_praha/zmelik_klatovy.png"},
                {name: 'Slavkov u Brna', lon: 16.8764, lat: 49.1531, image: "../foto_praha/slavkov_u_brna.jpg"},
                {name: 'Vyškov', lon: 16.9989, lat: 49.2775, image: "../foto_praha/vyskov.jpg"},
                {name: 'Vídeň', lon: 16.3738, lat: 48.2082, image: "../foto_praha/zmelik_viden.jpg"},
                {name: 'Prešpurk (dnes Bratislava)', lon: 17.1077, lat: 48.1486, image: "../foto_praha/zmelik_prespurk.png"},
                {name: 'Ulm', lon: 9.9876, lat: 48.4011, image: "../foto_praha/ulm.png"},
                {name: 'Drážďany', lon: 13.7373, lat: 51.0504, image: "../foto_praha/drazdany.jpg"},
                {name: 'Lipsko', lon: 12.360103, lat: 51.340199, image: "../foto_praha/lipsko.jpeg"},
            ]},
            {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
                {name: 'Žitná brána (zbořena 1875)', lon: 14.4305, lat: 50.0798, image: "../foto_praha/zitna_brana.jpg"},
                {name: 'Koňská brána (zbořena 1875)', lon: 14.429, lat: 50.0815, image: "../foto_praha/storzer_konska_brana.jpg"},
            ]},]});
            break;
        case "flvek5":
            Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.4185, 50.086], zoom: 6}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: ''}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
            {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
                {name: 'Hradčany', lon: 14.399, lat: 50.0894, image: "../foto_praha/hradcany.jpg"},
                {name: 'Hradčanské náměstí', lon: 14.3985, lat: 50.089, image: "../foto_praha/storzer_hradcanske_n.jpg"},
                {name: 'Strahovský klášter (Strahov)', lon: 14.3895, lat: 50.0855, image: "../foto_praha/strahovsky_klaster.jpg"},
                {name: 'Loreta', lon: 14.3925, lat: 50.0892, image: "../foto_praha/loreta.jpg"},
                {name: 'Petřín', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin.jpg"},
                {name: 'Malá Strana', lon: 14.404, lat: 50.0884, image: "../foto_praha/mala_strana.jpg"},
                {name: 'Ostruhová ulice (dnes Nerudova), Malá Strana', lon: 14.3995, lat: 50.0883, image: "../foto_praha/ostruhova.jpg"},
                {name: 'Mostecká ulice', lon: 14.406, lat: 50.0875, image: "../foto_praha/mosteckaulice.jpg"},
                {name: 'Fürstenberská zahrada', lon: 14.4025, lat: 50.0905, image: "../foto_praha/zmelik_furstenberska_zahrada.jpg"},
                {name: 'Nosticova zahrada', lon: 14.403, lat: 50.0868, image: "../foto_praha/nosticova_zahrada.jpg"},
                {name: 'Újezd', lon: 14.404, lat: 50.083, image: "../foto_praha/ujezd.jpg"},
                {name: 'Karlův most', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluvmost.jpg"},
                {name: 'Vltava', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava.jpg"},
                {name: 'Střelecký ostrov', lon: 14.4115, lat: 50.0815, image: "../foto_praha/streleckyostrov.jpg"},
                {name: 'Staré Město', lon: 14.421, lat: 50.0875, image: "../foto_praha/staremesto.jpg"},
                {name: 'Staroměstské náměstí', lon: 14.4205, lat: 50.0875, image: "../foto_praha/staromestskenamesti.jpg"},
                {name: 'Celetná ulice', lon: 14.425, lat: 50.0876, image: "../foto_praha/zmelik_celetna.jpg"},
                {name: 'Železná ulice', lon: 14.422, lat: 50.0855, image: "../foto_praha/zelezna_ulice.jpg"},
                {name: 'Jilská ulice', lon: 14.418, lat: 50.0855, image: "../foto_praha/jilska_ulice_praha.jpg"},
                {name: 'Dominikánská ulice (dnes Husova)', lon: 14.4185, lat: 50.0858, image: "../foto_praha/dominikanska.jpg"},
                {name: 'Jezuitská ulice (dnes Karlova)', lon: 14.417, lat: 50.086, image: "../foto_praha/jezuitska_ulice.jpg"},
                {name: 'Kozí ulice', lon: 14.422, lat: 50.0905, image: "../foto_praha/kozi_ulice.jpg"},
                {name: 'Havířská ulice', lon: 14.425, lat: 50.0865, image: "../foto_praha/havirska_ulice.jpg"},
                {name: 'Králodvorská ulice', lon: 14.428, lat: 50.0885, image: "../foto_praha/kralodvorska_ulice.jpg"},
                {name: 'Prašná brána', lon: 14.428, lat: 50.0875, image: "../foto_praha/storzer_prasnab.jpg"},
                {name: 'Nové Město', lon: 14.427, lat: 50.078, image: "../foto_praha/novemesto.jpg"},
                {name: 'Václavské náměstí (dříve Koňský trh)', lon: 14.428, lat: 50.081, image: "../foto_praha/Storzer_vaclavak.jpg"},
                {name: 'Karlovo náměstí (dříve Dobytčí trh)', lon: 14.42, lat: 50.076, image: "../foto_praha/karlovonamesti_svejk.jpg"},
                {name: 'Spálená ulice', lon: 14.4195, lat: 50.0805, image: "../foto_praha/spalena_ulice.jpeg"},
                {name: 'Ječná ulice', lon: 14.423, lat: 50.0755, image: "../foto_praha/jecna_svejk.jpg"},
                {name: 'Žitná ulice', lon: 14.425, lat: 50.0775, image: "../foto_praha/zmelik_zitna_ulice.jpg"},
                {name: 'Olšanské hřbitovy', lon: 14.472, lat: 50.083, image: "../foto_praha/zmelik_olsany.jpg"},
                {name: 'Libeň', lon: 14.47, lat: 50.11, image: "../foto_praha/liben_svejk.jpg"},
                {name: 'Smíchov', lon: 14.404, lat: 50.071, image: "../foto_praha/smichov.jpg"},
                {name: 'Vyšehrad', lon: 14.4176, lat: 50.0641, image: "../foto_praha/vysehrad.jpg"},
                {name: 'Bílá hora', lon: 14.317, lat: 50.081, image: "../foto_praha/zmelik_bila_hora.jpg"},
                {name: 'Litomyšl', lon: 16.311, lat: 49.872, image: "../foto_praha/litomysl.jpg"},
                {name: 'Dobruška', lon: 16.161, lat: 50.292, image: "../foto_praha/dobruska.jpg"},
                {name: 'Dobřany (okr. Rychnov n. Kn.)', lon: 16.273, lat: 50.264, image: "../foto_praha/dobrany.jpg"},
                {name: 'Solnice', lon: 16.238, lat: 50.244, image: "../foto_praha/solnice.jpg"},
                {name: 'Opočno', lon: 16.115, lat: 50.27, image: "../foto_praha/opocno.jpg"},
                {name: 'Rychnov nad Kněžnou', lon: 16.275, lat: 50.163, image: "../foto_praha/rychnov_nad_kneznou.png"},
                {name: 'Vamberk', lon: 16.29, lat: 50.123, image: "../foto_praha/vamberk.jpg"},
                {name: 'Náchod', lon: 16.166, lat: 50.415, image: "../foto_praha/storzer_nachod.jpg"},
                {name: 'Hradec Králové', lon: 15.833, lat: 50.209, image: "../foto_praha/hradec_kralove.jpeg"},
                {name: 'Josefov (pevnost, Jaroměř)', lon: 15.928, lat: 50.337, image: "../foto_praha/storzer_josefov.jpg"},
                {name: 'Jezbiny (u Josefova)', lon: 15.945, lat: 50.345, image: "../foto_praha/jezbiny.jpg"},
                {name: 'Vídeň', lon: 16.373, lat: 48.208, image: "../foto_praha/zmelik_viden.jpg"},
                {name: 'Drážďany', lon: 13.737, lat: 51.05, image: "../foto_praha/drazdany.jpg"},
                {name: 'Lipsko', lon: 12.375, lat: 51.34, image: "../foto_praha/lipsko.jpeg"},
                {name: 'Weissenfels', lon: 11.97, lat: 51.2, image: "../foto_praha/weissenfels.jpg"},
                {name: 'Berlín', lon: 13.405, lat: 52.52, image: "../foto_praha/storzer_berlin.jpg"},
                {name: 'Kladsko (Kłodzko)', lon: 16.66, lat: 50.435, image: "../foto/kladsko.png"},
                {name: 'Mladá Boleslav', lon: 14.903, lat: 50.411, image: "../foto/zmelik_mlada_boleslav.jpg"},
            ]},
            {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
                {name: 'Koňská brána (zbořena 1875)', lon: 14.429, lat: 50.0807, image: "../foto_praha/storzer_konska_brana.jpg"},
                {name: 'Novoměstská brána (zbořena 1898)', lon: 14.429, lat: 50.0758, image: "../foto_praha/novomestska_brana.jpg"},
                {name: 'Poříčská brána (zaniklá)', lon: 14.436, lat: 50.0905, image: "../foto_praha/storzer_poricskab.png"},
            ]},]});
            break;

        // POKRAČOVAT

        case "temno":
            Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [14.42075, 50.08675], zoom: 5}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: ''}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
            {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
                {name: 'Hradčany', lon: 14.399, lat: 50.0894, image: "../foto_praha/hradcany.jpg"},
                {name: 'Strahovský klášter', lon: 14.3895, lat: 50.0855, image: "../foto_praha/strahovsky_klaster.jpg"},
                {name: 'Loreta', lon: 14.3925, lat: 50.0892, image: "../foto_praha/loreta.jpg"},
                {name: 'Malá Strana', lon: 14.404, lat: 50.0884, image: "../foto_praha/malastrana.jpg"},
                {name: 'Ostruhová ulice (dnes Nerudova)', lon: 14.4007, lat: 50.0883, image: "../foto_praha/ostruhova.jpg"},
                {name: 'Karlův most', lon: 14.4114, lat: 50.0865, image: "../foto_praha/karluvmost.jpg"},
                {name: 'Kampa', lon: 14.4075, lat: 50.0858, image: "../foto_praha/kampa.jpg"},
                {name: 'Vltava', lon: 14.411, lat: 50.086, image: "../foto_praha/vltava.jpg"},
                {name: 'Petřín', lon: 14.3915, lat: 50.0835, image: "../foto_praha/petrin.jpg"},
                {name: 'Staré Město', lon: 14.421, lat: 50.0875, image: "../foto_praha/staremesto.jpg"},
                {name: 'Staroměstské náměstí', lon: 14.421, lat: 50.0875, image: "../foto_praha/staromestskenamesti.jpg"},
                {name: 'Týnský chrám', lon: 14.4222, lat: 50.0879, image: "../foto_praha/tynskychram.jpg"},
                {name: 'Betlémská kaple', lon: 14.4172, lat: 50.0846, image: "../foto_praha/betlemska_kaple.jpg"},
                {name: 'Klementinum', lon: 14.4156, lat: 50.0865, image: "../foto_praha/klementinum.jpg"},
                {name: 'Nové Město', lon: 14.427, lat: 50.078, image: "../foto_praha/novemesto.jpg"},
                {name: 'Koňský trh (dnes Václavské náměstí)', lon: 14.427, lat: 50.081, image: "../foto_praha/konsky_trh.jpg"},
                {name: 'Dobytčí trh (dnes Karlovo náměstí)', lon: 14.4205, lat: 50.0758, image: "../foto_praha/dobytci_trh.jpg"},
                {name: 'Spálená ulice', lon: 14.4195, lat: 50.081, image: "../foto_praha/spalena_ulice.jpeg"},
                {name: 'Vyšehrad', lon: 14.4176, lat: 50.0641, image: "../foto_praha/vysehrad.jpg"},
                {name: 'Podskalí', lon: 14.415, lat: 50.066, image: "../foto_praha/zmelik_podskali.jpg"},
                {name: 'Smíchov', lon: 14.404, lat: 50.071, image: "../foto_praha/smichov.jpg"},
                {name: 'Žižkov', lon: 14.449, lat: 50.087, image: "../foto_praha/storzer_zizkov.JPG"},
                {name: 'Vinohrady', lon: 14.448, lat: 50.0755, image: "../foto_praha/storzer_vinohrady.jpg"},
                {name: 'Libeň', lon: 14.469, lat: 50.108, image: "../foto_praha/liben_svejk.jpg"},
                {name: 'Josefov', lon: 14.418, lat: 50.09, image: "../foto_praha/storzer_josefov.jpg"},
                {name: 'Bílá hora', lon: 14.318, lat: 50.082, image: "../foto_praha/zmelik_bila_hora.jpg"},
                {name: 'Skalka (tvrz u Dobrušky)', lon: 16.155, lat: 50.298, image: "../foto_praha/skalka.jpg"},
                {name: 'Dobruška', lon: 16.1606, lat: 50.2906, image: "../foto_praha/dobruska.jpg"},
                {name: 'Opočno', lon: 16.1147, lat: 50.2706, image: "../foto_praha/opocno.jpg"},
                {name: 'Meziříčí (u Dobrušky)', lon: 16.137, lat: 50.296, image: "../foto_praha/mezirici.jpg"},
                {name: 'Kopidlno', lon: 15.2747, lat: 50.3308, image: "../foto_praha/kopidlno.jpg"},
                {name: 'Jičín', lon: 15.3517, lat: 50.4361, image: "../foto_praha/zmelik_jicin.jpg"},
                {name: 'Hradec Králové', lon: 15.8328, lat: 50.2092, image: "../foto_praha/hradec_kralove.jpeg"},
                {name: 'Náchod', lon: 16.1656, lat: 50.4156, image: "../foto_praha/storzer_nachod.jpg"},
                {name: 'Poděbrady', lon: 15.1186, lat: 50.1425, image: "../foto_praha/podebrady.jpg"},
                {name: 'Vídeň', lon: 16.3738, lat: 48.2082, image: "../foto_praha/zmelik_viden.jpg"},
                {name: 'Řím', lon: 12.4964, lat: 41.9028, image: "../foto_praha/rim.jpg"},
            ]},
            {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [
                {name: 'Žitná brána (zbořena 1875)', lon: 14.4305, lat: 50.0798, image: "../foto_praha/zitna_brana.jpg"},
                {name: 'Koňská brána (zbořena 1875)', lon: 14.429, lat: 50.0815, image: "../foto_praha/storzer_konska_brana.jpg"},
            ]},]});
            break;
        case "psohlavci":
            Highcharts.mapChart('gis-container', {chart: {margin: 0}, title: {text: ''}, navigation: {buttonOptions: {align: 'left', theme: {stroke: '#e6e6e6'}}}, mapNavigation: {enabled: true, buttonOptions: {alignTo: 'spacingBox'}}, mapView: {center: [12.9241, 49.4175], zoom: 6}, tooltip: {useHTML: true, headerFormat: "{point.point.name}", pointFormat: '<br/><img src="{point.image}"/>'}, legend: {enabled: true, title: {text: ''}, align: 'right', symbolWidth: 20, symbolHeight: 20, itemStyle: {textOutline: '1 1 1px rgba(255,255,255)'}, backgroundColor: 'rgba(255,255,255,0.8)', float: true, borderColor: '#e6e6e6', borderWidth: 1, borderRadius: 2, itemMarginBottom: 5}, plotOptions: {mappoint: {dataLabels: {enabled: false}}}, series: [{type: 'tiledwebmap', name: '', provider: {type: 'OpenStreetMap'}, showInLegend: false},
            {type: 'mappoint', name: 'existing place', marker: {symbol: 'url(../img/placeholder.png)', width: 24, height: 24}, data: [
                {name: 'Újezd (rodná ves Jana Sladkého Koziny)', lon: 12.9189, lat: 49.4486, image: "../foto_praha/ujezd_dobruska.jpg"},
                {name: 'Trhanov (sídlo Lomikara)', lon: 12.8447, lat: 49.3897, image: "../foto_praha/trhanov.jpg"},
                {name: 'Domažlice', lon: 12.9293, lat: 49.4407, image: "../foto_praha/Storzer_domazlice.jpg"},
                {name: 'Chodov', lon: 12.8869, lat: 49.4253, image: "../foto_praha/chodov.JPG"},
                {name: 'Draženov', lon: 12.8836, lat: 49.4561, image: "../foto_praha/drazenov.jpg"},
                {name: 'Postřekov', lon: 12.8333, lat: 49.4925, image: "../foto_praha/postrekov.jpg"},
                {name: 'Stráž', lon: 12.9036, lat: 49.4778, image: "../foto_praha/straz.jpg"},
                {name: 'Mrákov', lon: 12.9694, lat: 49.4006, image: "../foto_praha/mrakov.jpg"},
                {name: 'Tlumačov', lon: 12.9897, lat: 49.4097, image: "../foto_praha/tlumacov.jpg"},
                {name: 'Pocínovice', lon: 13.0508, lat: 49.3611, image: "../foto_praha/pocinovice.jpg"},
                {name: 'Klenčí pod Čerchovem', lon: 12.8133, lat: 49.4314, image: "../foto_praha/klenci_pod_cerchovem.jpg"},
                {name: 'Kýčov (Klíčov)', lon: 12.9853, lat: 49.3939, image: "../foto_praha/kycov.jpg"},
                {name: 'Chodská Lhota', lon: 13.0231, lat: 49.3753, image: "../foto_praha/chodska_lhota.jpg"},
                {name: 'Čerchov (nejvyšší vrch Českého lesa)', lon: 12.7775, lat: 49.3839, image: "../foto_praha/cerchov.jpg"},
                {name: 'Všeruby (Všerubský průsmyk)', lon: 12.9986, lat: 49.3331, image: "../foto_praha/vseruby.jpg"},
                {name: 'Plzeň', lon: 13.3776, lat: 49.7475, image: "../foto_praha/Storzer_plzen.jpg"},
                {name: 'Praha (poprava Koziny na Koňském trhu, dnes Václavské nám.)', lon: 14.428, lat: 50.081, image: "../foto_praha/konsky_trh.jpg"},
                {name: 'Vídeň (Kozinova apelace k císaři)', lon: 16.3738, lat: 48.2082, image: "../foto_praha/zmelik_viden.jpg"},
            ]},
            {type: 'mappoint', name: 'vanished place', marker: {symbol: 'url(../img/maps-and-flags.png)', width: 24, height: 24}, data: [

            ]},]});
            break;
    default:
            document.getElementById("gis-container").innerHTML = "";
    }
}
