function showNetworkGraph() {
  var option = document.getElementById("cluster").value;
  
  const vypravec = '#c4688c',
  postava = '#78a8d1', // postava, se kterou vypravěč nebo jiná postava explicitně komunikuje
  postava2 = '#aeb6bf'; // postava, se kterou vypravěč nebo jiná postava explicitně nekomunikuje, ale komunikace je vyprávěna (např. "promluvil jsem si s X")
  
  const line = '#000000';
  const linewidth = 2.0;

  switch(option){
    case "peklazplozenci":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Pekla zplozenci'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Abigaila"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Scota", "hlas"],
                    ["hlas", "Scota"],
                    ["hlas", "Scota"],
                    ["Scota", "hlas"],
                    ["host", "Lang"],
                    ["Lang", "host"],
                    ["host", "Lang"],
                    ["host", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Jiřina"],
                    ["Geisler", "Jiřina"],
                    ["Jiřina", "Geisler"],
                    ["Jiřina", "Geisler"],
                    ["Geisler", "Jiřina"],
                    ["Jiřina", "Geisler"],
                    ["Jiřina", "Geisler"],
                    ["Geisler", "Jiřina"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "reholnik"],
                    ["reholnik", "Lang"],
                    ["Lang", "reholnik"],
                    ["Lang", "reholnik"],
                    ["Filomén", "Lang"],
                    ["Lang", "Filomén"],
                    ["Lang", "Filomén"],
                    ["Lang", "Filomén"],
                    ["Filomén", "Lang"],
                    ["Filomén", "Lang"],
                    ["Lang", "Filomén"],
                    ["Lang", "Filomén"],
                    ["Filomén", "Lang"],
                    ["Lang", "Filomén"],
                    ["Filomén", "Lang"],
                    ["Filomén", "Lang"],
                    ["Lang", "Filomén"],
                    ["Lang", "Filomén"],
                    ["Filomén", "Lang"],
                    ["Lang", "Filomén"],
                    ["Filomén", "Lang"],
                    ["Lang", "Filomén"],
                    ["Lang", "Filomén"],
                    ["Filomén", "Lang"],
                    ["Filomén", "Lang"],
                    ["Geisler", "Lang"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Abigaila", "Vilém"],
                    ["Abigaila", "Vilém"],
                    ["Vilém", "Abigaila"],
                    ["Abigaila", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Jiřina", "Lang"],
                    ["Lang", "Jiřina"],
                    ["Lang", "Jiřina"],
                    ["Jiřina", "Lang"],
                    ["Jiřina", "Lang"],
                    ["Jiřina", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Abigaila", "Vilém"],
                    ["Vilém", "Abigaila"],
                    ["Vilém", "Abigaila"],
                    ["Abigaila", "Vilém"],
                    ["Vilém", "Abigaila"],
                    ["Abigaila", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Scota"],
                    ["Scota", "Vilém"],
                    ["Vilém", "Abigaila"],
                    ["Scota", "Abigaila"],
                    ["Scota", "Abigaila"],
                    ["Abigaila", "Scota"],
                    ["Abigaila", "Vilém"],
                    ["Abigaila", "Vilém"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Kohounová", "Lang"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Lang", "Kohounová"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Lang", "Kohounová"],
                    ["Kohounová", "Lang"],
                    ["Kohounová", "Lang"],
                    ["Lang", "Kohounová"],
                    ["Lang", "Kohounová"],
                    ["Lang", "Kohounová"],
                    ["Panigarola", "Fermensemmel"],
                    ["Panigarola", "Paspedillo"],
                    ["Paspedillo", "Panigarola"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Paspedillo", "Panigarola"],
                    ["Paspedillo", "Panigarola"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Fermensemmel", "Paspedillo"],
                    ["Paspedillo", "Fermensemmel"],
                    ["Kolumbánský", "Fermensemmel"],
                    ["Paspedillo", "Panigarola"],
                    ["Panigarola", "Fermensemmel"],
                    ["Panigarola", "Fermensemmel"],
                    ["Fermensemmel", "Panigarola"],
                    ["Fermensemmel", "Panigarola"],
                    ["Paspedillo", "Kolumbánský"],
                    ["Kolumbánský", "Paspedillo"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Lang", "Jiřina"],
                    ["Jiřina", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Geisler", "Lang"],
                    ["Lang", "Geisler"],
                    ["Lang", "Geisler"],
                    ["Rudolf", "Reder"],
                    ["Reder", "Rudolf"],
                    ["Reder", "Rudolf"],
                    ["Rudolf", "Reder"],
                    ["aga", "Reder"],
                    ["Reder", "aga"],
                    ["Rudolf", "Reder"],
                    ["Reder", "Rudolf"],
                    ["Rudolf", "Reder"],
                    ["Rudolf", "Geisler"],
                    ["Geisler", "Lang"],
                    ["Vilém", "Sempiterna"],
                    ["Vilém", "Sempiterna"],
                    ["Vilém", "Sempiterna"],
                    ["Vilém", "Sempiterna"],
                    ["Sempiterna", "Vilém"],
                    ["Vilém", "Sempiterna"],
                    ["Vilém", "Scota"],
                    ["Vilém", "Scota"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Geisler", "Scota"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Lang"],
                    ["Lang", "Scota"],
                    ["Lang", "Scota"],
                    ["Scota", "Lang"],
                    ["Scota", "Lang"],
                    ["Scota", "Lang"],
                    ["Lang", "Scota"],
                    ["Lang", "Scota"],
                    ["Scota", "Lang"],
                    ["Lang", "Scota"],
                    ["Scota", "Lang"],
                    ["Scota", "Lang"],
                    ["Scota", "Lang"],
                    ["Lang", "Scota"],
                    ["Scota", "Lang"],
                    ["Lang", "Scota"],
                    ["Scota", "Lang"],
                    ["Lang", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Scota", "Geisler"],
                    ["Geisler", "Scota"],
                    ["Lang", "Jiřina"],
                    ["Jiřina", "Lang"],
                    ["Lang", "Jiřina"],
                    ["Vilém", "Filomén"],
                    ["Filomén", "Vilém"],
                    ["Vilém", "Filomén"],
                    ["Filomén", "Vilém"],
                    ["Jošt", "Vilém"],
                    ["Jošt", "Vilém"],
                    ["Vilém", "Jošt"],
                    ["Vilém", "Jošt"],
                    ["Jošt", "Vilém"],
                    ["Jošt", "Vilém"],
                    ["Vilém", "Jošt"],
                    ["Filomén", "Vilém"],
                    ["Filomén", "Jošt"],
                    ["Vilém", "Filomén"],
                    ["Jošt", "Filomén"],
                    ["Vilém", "Abigaila"],
                    ["Filomén", "Vilém"],
                    ["Filomén", "Jošt"],
                    ["Vilém", "Filomén"],
                    ["Jošt", "Filomén"],
                    ["Abigaila", "Vilém"],
                    ["Abigaila", "Jošt"],
                    ["Vilém", "Abigaila"],
                    ["Jošt", "Abigaila"],
                    ["Panigarola", "Fermensemmel"],
                    ["Paspedillo", "Panigarola"],
                    ["Fermensemmel", "Paspedillo"],
                    ["Paspedillo", "Fermensemmel"],
                    ["Kolumbánský", "Fermensemmel"],
                    ["Panigarola", "Kolumbánský"],
                    ["Kolumbánský", "Panigarola"],
                    ["Fermensemmel", "Paspedillo"],
                    ["Paspedillo", "Fermensemmel"],
                    ["Panigarola", "Fermensemmel"],
                    ["Kolumbánský", "Fermensemmel"],
                    ["Fermensemmel", "Kolumbánský"],
                    ["Kolumbánský", "Fermensemmel"],
                    ["Lang", "Fermensemmel"],
                    ["Lang", "Fermensemmel"],
                    ["Fermensemmel", "Lang"],
                    ["Lang", "Fermensemmel"],
                    ["Fermensemmel", "Lang"],
                    ["Kolumbánský", "Fermensemmel"],
                    ["Fermensemmel", "Kolumbánský"],
                    ["Kolumbánský", "Fermensemmel"],
                    ["Kolumbánský", "Fermensemmel"],
                    ["Fermensemmel", "Kolumbánský"],
                    ["Lang", "Fermensemmel"],
                    ["Lang", "Fermensemmel"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Lang", "Rudolf"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Lang", "Rudolf"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Lang"],
                    ["Rudolf", "Geisler"],
                    ["Geisler", "Rudolf"],
                    ["Rudolf", "Geisler"],
                    ["Rudolf", "Lang"],

                ], nodes: 

                    [


                    // hlavní postavy

                    {id: 'Lang',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Scota',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Vilém',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Geisler',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Rudolf',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Kohounová',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Filomén',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Abigaila',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Jiřina',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Jošt',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'hlas',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'host',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'reholnik',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Panigarola',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Fermensemmel',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Paspedillo',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kolumbánský',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Reder',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'aga',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Sempiterna',marker: {radius: 10,lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
    default:
    document.getElementById("container-person").src = "";   
  }
}






// ŠABLONA:

/*
    case "NÁZEV CASE-TEXTU":
      Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'NÁZEV TEXTU'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
        
                    ["narrator", "JMÉNO POSTAVY"],
                    ...
                    
                ], nodes: 
                    [
                    // vypravěč
                    {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},

                    // hlavní postavy
                    {id: 'NÁZEV POSTAVY 1',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    ...

                    // vedlejší postavy
                    {id: 'NÁZEV POSTAVY 2',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    ...

                    ]
                }
              ]
          });
      break;
*/