function showNetworkGraph() {
  var option = document.getElementById("cluster").value;
  
  const vypravec = '#c4688c',
  postava = '#78a8d1', // postava, se kterou vypravěč nebo jiná postava explicitně komunikuje
  postava2 = '#aeb6bf'; // postava, se kterou vypravěč nebo jiná postava explicitně nekomunikuje, ale komunikace je vyprávěna (např. "promluvil jsem si s X")
  
  const line = '#000000';
  const linewidth = 2.0;

  switch(option){
    case "cernypetricek":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Černý Petříček'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["učedník", "Petříček"],
                    ["Petříček", "učedník"],
                    ["učedník", "Petříček"],
                    ["Petříček", "učedník"],
                    ["učedník", "Petříček"],
                    ["Petříček", "učedník"],
                    ["kuchařka", "Petříček"],
                    ["Petříček", "kuchařka"],
                    ["kuchařka", "Petříček"],
                    ["Petříček", "kuchařka"],
                    ["kuchařka", "Petříček"],
                    ["Petříček", "kuchařka"],
                    ["kotlář", "Petříček"],
                    ["Petříček", "kotlář"],
                    ["kotlář", "Petříček"],
                    ["Petříček", "kotlář"],
                    ["kotlář", "Petříček"],
                    ["Petříček", "kotlář"],
                    ["kozák", "matka"],
                    ["matka", "kozák"],
                    ["kozák", "Petříček"],
                    ["Petříček", "kozák"],
                    ["kozák", "matka"],
                    ["matka", "kozák"],
                    ["matka", "Petříček"],
                    ["Petříček", "matka"],
                    ["panímaminka", "matka"],
                    ["matka", "panímaminka"],
                    ["panímaminka", "Petříček"],
                    ["Petříček", "panímaminka"],
                    ["panímaminka", "Petříček"],
                    ["Petříček", "panímaminka"],
                    ["matka", "Petříček"],
                    ["Petříček", "matka"],
                    ["učitel", "Petříček"],
                    ["Petříček", "učitel"],
                    ["učitel", "Petříček"],
                    ["Petříček", "učitel"],
                    ["Stázička", "Petříček"],
                    ["Petříček", "Stázička"],
                    ["panímaminka", "Petříček"],
                    ["Petříček", "panímaminka"],
                    ["panímaminka", "Petříček"],
                    ["Petříček", "panímaminka"],
                    ["panímaminka", "Petříček"],
                    ["Petříček", "panímaminka"],
                    ["panímaminka", "Petříček"],
                    ["Petříček", "panímaminka"],
                    ["František", "Stázička"],
                    ["Stázička", "František"],
                    ["František", "Stázička"],
                    ["Stázička", "František"],
                    ["páter Josef", "panímaminka"],
                    ["panímaminka", "páter Josef"],
                    ["páter Josef", "František"],
                    ["František", "páter Josef"],
                    ["páter Josef", "panímaminka"],
                    ["panímaminka", "páter Josef"],
                    ["Petříček", "panímaminka"],
                    ["panímaminka", "Petříček"],
                    ["Petříček", "Stázička"],
                    ["Stázička", "Petříček"],
                    ["František", "Stázička"],
                    ["Stázička", "František"],
                    ["Stázička", "Petříček"],
                    ["Petříček", "Stázička"],
                    ["Stázička", "Petříček"],
                    ["Petříček", "Stázička"],
                    ["Petříček", "František"],
                    ["František", "Petříček"],
                    ["Petříček", "František"],
                    ["František", "Petříček"],
                    ["Petříček", "František"],
                    ["František", "Petříček"],
                    ["Stázička", "panímaminka"],
                    ["panímaminka", "Stázička"],
                    ["Stázička", "panímaminka"],
                    ["panímaminka", "Stázička"],
                    ["Stázička", "panímaminka"],
                    ["panímaminka", "Stázička"],
                    ["Stázička", "panímaminka"],
                    ["panímaminka", "Stázička"],
                    ["tandlířka", "Petříček"],
                    ["Petříček", "tandlířka"],
                    ["tandlířka", "Petříček"],
                    ["Petříček", "tandlířka"],
                    ["panímaminka", "tandlířka"],
                    ["tandlířka", "panímaminka"],
                    ["panímaminka", "Stázička"],
                    ["Stázička", "panímaminka"],
                    ["panímaminka", "Stázička"],
                    ["Stázička", "panímaminka"],
                    ["František", "Stázička"],
                    ["Stázička", "František"],
                    ["František", "Stázička"],
                    ["Stázička", "František"],
                    ["Stázička", "Václav"],
                    ["Václav", "Stázička"],
                    ["Stázička", "Václav"],
                    ["Václav", "Stázička"],
                    ["Václav", "pláteník"],
                    ["pláteník", "Václav"],
                    ["Václav", "panímaminka"],
                    ["panímaminka", "Václav"],
                    ["Stázička", "Petříček"],
                    ["Petříček", "Stázička"],
                    ["Stázička", "Petříček"],
                    ["Petříček", "Stázička"],
                    ["Petříček", "panímaminka"],
                    ["panímaminka", "Petříček"],
                    ["páter Josef", "Stázička"],
                    ["Stázička", "páter Josef"],
                    ["páter Josef", "Stázička"],
                    ["Stázička", "páter Josef"],

                ], nodes: 

                    [

                    // hlavní postavy

                    {id: 'Petříček',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Stázička',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'František',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'panímaminka',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'učedník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'kuchařka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'kotlář',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'kozák',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'matka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'učitel',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'páter Josef',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'tandlířka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Václav',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'pláteník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                }
              ]
          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
      case "mladapanizapletalova":
      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Mladá paní Zapletalová'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["František", "Tereza"],
                    ["Tereza", "František"],
                    ["František", "Tereza"],
                    ["Tereza", "František"],
                    ["František", "Tereza"],
                    ["Tereza", "František"],
                    ["František", "Tereza"],
                    ["Teofíl", "Anděla"],
                    ["Teofíl", "Anděla"],
                    ["Teofíl", "František"],
                    ["Teofíl", "Anděla"],
                    ["Teofíl", "Anděla"],
                    ["Teofíl", "František"],
                    ["Anděla", "Teofíl"],
                    ["Teofíl", "Anděla"],
                    ["František", "Teofíl"],
                    ["Teofíl", "František"],
                    ["František", "Teofíl"],
                    ["Teofíl", "Anděla"],
                    ["Anděla", "Teofíl"],
                    ["Teofíl", "Anděla"],
                    ["František", "Teofíl"],
                    ["Teofíl", "František"],
                    ["František", "Teofíl"],
                    ["Teofíl", "František"],
                    ["stará paní", "Tereza"],
                    ["Tereza", "stará paní"],
                    ["stará paní", "Tereza"],
                    ["Tereza", "stará paní"],
                    ["stará paní", "Tereza"],
                    ["Tereza", "stará paní"],
                    ["stará paní", "Tereza"],
                    ["Tereza", "stará paní"],
                    ["stará paní", "Tereza"],
                    ["abatyše", "dívky"],
                    ["dívky", "abatyše"],
                    ["abatyše", "Anděla"],
                    ["Anděla", "abatyše"],
                    ["Teofíl", "Anděla"],
                    ["Adolar", "Anděla"],
                    ["Anděla", "Adolar"],
                    ["Anděla", "Adolar"],
                    ["Adolar", "Anděla"],
                    ["Anděla", "Adolar"],
                    ["Adolar", "Anděla"],
                    ["Tereza", "Anděla"],
                    ["Anděla", "Tereza"],
                    ["Tereza", "Anděla"],
                    ["Anděla", "Tereza"],
                    ["František", "Tereza"],
                    ["Tereza", "František"],
                    ["František", "Tereza"],
                    ["Tereza", "František"],
                    ["František", "Tereza"],
                    ["Tereza", "František"],
                    ["František", "Tereza"],
                    ["Teofíl", "František"],
                    ["Teofíl", "Tereza"],
                    ["Adolar", "Teofíl"],
                    ["Teofíl", "Adolar"],
                    ["Tereza", "kočí"],
                    ["kočí", "Tereza"],
                    ["Adolar", "Teofíl"],
                    ["Teofíl", "Adolar"],
                    ["František", "Tereza"],
                    ["František", "Tereza"],
                    ["Tereza", "František"],
                    ["Tereza", "Teofíl"],
                    ["Teofíl", "Tereza"],
                    ["Anděla", "Teofíl"],
                    ["Tereza", "Teofíl"],
                    ["Teofíl", "Tereza"],
                    ["převor", "Teofíl"],
                    ["Teofíl", "převor"],
                    ["převor", "Teofíl"],
                    ["Teofíl", "František"],
                    ["Teofíl", "František"],
                    ["František", "Teofíl"],
                    ["Teofíl", "František"],
                    ["František", "Teofíl"],
                    ["Teofíl", "František"],
                    ["František", "Teofíl"],

                ], nodes: 

                    [

                    // hlavní postavy

                    {id: 'Anděla',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'František',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Tereza',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Teofíl',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'stará paní',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'abatyše',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'dívky',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Adolar',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'kočí',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'převor',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
      case "zvoneckovakralovna":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Zvonečková královna'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["babička", "Xavera"],
                    ["Klement", "kočí"],
                    ["kočí", "Klement"],
                    ["Klement", "kočí"],
                    ["Klement", "kočí"],
                    ["Leokad", "kočí"],
                    ["Leokad", "kočí"],
                    ["kočí", "Leokad"],
                    ["Leokad", "Klement"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Leokad", "Klement"],
                    ["Leokad", "Klement"],
                    ["Klement", "Leokad"],
                    ["Leokad", "Klement"],
                    ["Leokad", "Klement"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Klement", "Leokad"],
                    ["Leokad", "Klement"],
                    ["Leokad", "Klement"],
                    ["Leokad", "Klement"],
                    ["Leokad", "Klement"],
                    ["Klement", "Leokad"],
                    ["Klement", "Nattererová"],
                    ["Nattererová", "Klement"],
                    ["Klement", "Nattererová"],
                    ["Nattererová", "Klement"],
                    ["Klement", "Nattererová"],
                    ["Leokad", "Klement"],
                    ["Inocenc", "babička"],
                    ["Inocenc", "babička"],
                    ["Inocenc", "babička"],
                    ["babička", "Inocenc"],
                    ["Inocenc", "babička"],
                    ["Inocenc", "babička"],
                    ["babička", "Inocenc"],
                    ["babička", "Inocenc"],
                    ["Inocenc", "babička"],
                    ["Inocenc", "babička"],
                    ["Xavera", "klíčnice"],
                    ["Xavera", "klíčnice"],
                    ["klíčnice", "Xavera"],
                    ["klíčnice", "Xavera"],
                    ["Xavera", "klíčnice"],
                    ["Xavera", "klíčnice"],
                    ["klíčnice", "Xavera"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Nattererová", "hofmistryně"],
                    ["Nattererová", "hofmistryně"],
                    ["Nattererová", "Klement"],
                    ["hofmistryně", "Nattererová"],
                    ["hofmistryně", "Nattererová"],
                    ["hofmistryně", "Nattererová"],
                    ["hofmistryně", "Nattererová"],
                    ["hofmistryně", "Nattererová"],
                    ["Nattererová", "Leokad"],
                    ["Nattererová", "Leokad"],
                    ["Nattererová", "Leokad"],
                    ["Nattererová", "Klement"],
                    ["Klement", "Nattererová"],
                    ["Klement", "Nattererová"],
                    ["Leokad", "Nattererová"],
                    ["Inocenc", "babička"],
                    ["Leokad", "Klement"],
                    ["Leokad", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["babička", "Inocenc"],
                    ["babička", "Inocenc"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "klíčnice"],
                    ["Xavera", "klíčnice"],
                    ["Xavera", "klíčnice"],
                    ["Xavera", "klíčnice"],
                    ["Xavera", "klíčnice"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "babička"],
                    ["babička", "Xavera"],
                    ["Xavera", "babička"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Xavera", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Inocenc", "Klement"],
                    ["Inocenc", "Klement"],
                    ["Inocenc", "Klement"],
                    ["Inocenc", "Klement"],
                    ["Inocenc", "Klement"],
                    ["Inocenc", "Klement"],
                    ["Inocenc", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Inocenc", "Klement"],
                    ["Inocenc", "Klement"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Klement", "Xavera"],
                    ["Xavera", "Klement"],
                    ["Bolzano", "Leokad"],
                    ["Leokad", "Bolzano"],
                    ["Nattererová", "Klement"],

                ], nodes: 

                    [

                    // hlavní postavy

                    {id: 'Xavera',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'babička',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Klement',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Leokad',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Inocenc',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'kočí',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Nattererová',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'klíčnice',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'hofmistryně',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Bolzano',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
      case "prvniceska":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'První Češka'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["Kateřina", "Bedřich"],
                    ["Bedřich", "Kateřina"],
                    ["Kateřina", "Bedřich"],
                    ["Bedřich", "Kateřina"],
                    ["lékař", "rada"],
                    ["rada", "lékař"],
                    ["lékař", "rada"],
                    ["rada", "lékař"],
                    ["rada", "kněz"],
                    ["kněz", "rada"],
                    ["rada", "kněz"],
                    ["kněz", "rada"],
                    ["rada", "setník"],
                    ["setník", "rada"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["setník", "rada"],
                    ["rada", "setník"],
                    ["Gabriela", "setník"],
                    ["setník", "Gabriela"],
                    ["lékař", "Gabriela"],
                    ["Gabriela", "lékař"],
                    ["lékař", "Gabriela"],
                    ["Gabriela", "lékař"],
                    ["Kateřina", "Jitka"],
                    ["Jitka", "Kateřina"],
                    ["Kateřina", "Jitka"],
                    ["Jitka", "Kateřina"],
                    ["Kateřina", "Jitka"],
                    ["Gabriela", "Kateřina"],
                    ["Kateřina", "Gabriela"],
                    ["Gabriela", "Kateřina"],
                    ["Kateřina", "Gabriela"],
                    ["babička", "Gabriela"],
                    ["Gabriela", "babička"],
                    ["babička", "Gabriela"],
                    ["Gabriela", "babička"],
                    ["babička", "Gabriela"],
                    ["Gabriela", "babička"],
                    ["Kateřina", "Jitka"],
                    ["Jitka", "Kateřina"],
                    ["babička", "Jitka"],
                    ["Jitka", "babička"],
                    ["babička", "Jitka"],
                    ["Jitka", "babička"],
                    ["babička", "Jitka"],
                    ["babička", "Kateřina"],
                    ["Kateřina", "babička"],
                    ["babička", "Kateřina"],
                    ["Kateřina", "babička"],
                    ["babička", "Gabriela"],
                    ["Gabriela", "babička"],
                    ["babička", "Gabriela"],
                    ["Gabriela", "babička"],
                    ["babička", "rada"],
                    ["rada", "babička"],
                    ["babička", "rada"],
                    ["rada", "babička"],
                    ["rada", "páže"],
                    ["páže", "rada"],
                    ["rada", "páže"],
                    ["páže", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "domovník"],
                    ["domovník", "rada"],
                    ["rada", "domovník"],
                    ["domovník", "rada"],
                    ["babička", "Melichar"],
                    ["Melichar", "babička"],
                    ["babička", "Melichar"],
                    ["Melichar", "babička"],
                    ["babička", "Gabriela"],
                    ["Gabriela", "babička"],
                    ["Raimund", "rada"],
                    ["rada", "Raimund"],
                    ["Raimund", "rada"],
                    ["rada", "Raimund"],
                    ["Raimund", "rada"],
                    ["rada", "Raimund"],
                    ["rada", "Jitka"],
                    ["Jitka", "rada"],
                    ["rada", "Jitka"],
                    ["Jitka", "rada"],
                    ["rada", "Jitka"],
                    ["Raimund", "Emanuel"],
                    ["Emanuel", "Raimund"],
                    ["setník", "rada"],
                    ["rada", "setník"],
                    ["příbuzní", "rada"],
                    ["rada", "příbuzní"],
                    ["příbuzní", "rada"],
                    ["rada", "příbuzní"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["rada", "pojezdná"],
                    ["pojezdná", "rada"],
                    ["rada", "pojezdná"],
                    ["pojezdná", "rada"],
                    ["rada", "Gabriela"],
                    ["pojezdný", "pojezdná"],
                    ["pojezdná", "pojezdný"],
                    ["pojezdný", "pojezdná"],
                    ["pojezdná", "pojezdný"],
                    ["šafář", "pojezdný"],
                    ["pojezdný", "šafář"],
                    ["šafář", "pojezdný"],
                    ["pojezdný", "šafář"],
                    ["mušketýr", "Jitka"],
                    ["Jitka", "mušketýr"],
                    ["mušketýr", "Jitka"],
                    ["Jitka", "mušketýr"],
                    ["pojezdný", "mušketýr"],
                    ["mušketýr", "pojezdný"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["pojezdná", "mušketýr"],
                    ["mušketýr", "pojezdná"],
                    ["pojezdný", "pojezdná"],
                    ["pojezdná", "pojezdný"],
                    ["šafářka", "Jitka"],
                    ["Jitka", "šafářka"],
                    ["šafářka", "Jitka"],
                    ["Jitka", "šafářka"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Raimund", "Otilie"],
                    ["Otilie", "Raimund"],
                    ["Raimund", "Otilie"],
                    ["Otilie", "Raimund"],
                    ["Raimund", "Otilie"],
                    ["Otilie", "Raimund"],
                    ["Raimund", "Otilie"],
                    ["Otilie", "Raimund"],
                    ["Raimund", "Otilie"],
                    ["Otilie", "Raimund"],
                    ["Raimund", "Otilie"],
                    ["Otilie", "Raimund"],
                    ["mušketýr", "Jitka"],
                    ["Jitka", "mušketýr"],
                    ["mušketýr", "Jitka"],
                    ["Jitka", "mušketýr"],
                    ["mušketýr", "Jitka"],
                    ["Jitka", "mušketýr"],
                    ["Raimund", "Jitka"],
                    ["Jitka", "Raimund"],
                    ["Raimund", "Jitka"],
                    ["Jitka", "Raimund"],
                    ["Raimund", "Jitka"],
                    ["Jitka", "Raimund"],
                    ["Raimund", "Jitka"],
                    ["Jitka", "Raimund"],
                    ["rada", "pojezdný"],
                    ["pojezdný", "rada"],
                    ["rada", "pojezdný"],
                    ["pojezdný", "rada"],
                    ["rada", "Jitka"],
                    ["Jitka", "rada"],
                    ["rada", "Jitka"],
                    ["Jitka", "rada"],
                    ["rada", "Jitka"],
                    ["Otilie", "Emanuel"],
                    ["Emanuel", "Otilie"],
                    ["Otilie", "Emanuel"],
                    ["Emanuel", "Otilie"],
                    ["Otilie", "Emanuel"],
                    ["Emanuel", "Otilie"],
                    ["Otilie", "Emanuel"],
                    ["Emanuel", "Otilie"],
                    ["Emanuel", "Václav"],
                    ["Václav", "Emanuel"],
                    ["Emanuel", "Václav"],
                    ["Václav", "Emanuel"],
                    ["komorná", "Jitka"],
                    ["Jitka", "komorná"],
                    ["komorná", "Jitka"],
                    ["Jitka", "komorná"],
                    ["Gabriela", "Jitka"],
                    ["Jitka", "Gabriela"],
                    ["Gabriela", "Jitka"],
                    ["Jitka", "Gabriela"],
                    ["Gabriela", "Jitka"],
                    ["Gabriela", "Otilie"],
                    ["Otilie", "Gabriela"],
                    ["Gabriela", "Otilie"],
                    ["Otilie", "Gabriela"],
                    ["Gabriela", "Otilie"],
                    ["Otilie", "Gabriela"],
                    ["Gabriela", "Otilie"],
                    ["Otilie", "Gabriela"],
                    ["Jitka", "Václav"],
                    ["Václav", "Jitka"],
                    ["Jitka", "Václav"],
                    ["Václav", "Jitka"],
                    ["Jitka", "Václav"],
                    ["Václav", "Jitka"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Jitka", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Jitka", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Otilie", "Jitka"],
                    ["Jitka", "Otilie"],
                    ["rada", "Otilie"],
                    ["Otilie", "rada"],
                    ["Gabriela", "Jitka"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Vojtěch", "Jitka"],
                    ["Jitka", "Vojtěch"],
                    ["Emanuel", "Vojtěch"],
                    ["Vojtěch", "Emanuel"],
                    ["Emanuel", "Vojtěch"],
                    ["Vojtěch", "Emanuel"],
                    ["Emanuel", "Vojtěch"],
                    ["Vojtěch", "Emanuel"],
                    ["Emanuel", "Vojtěch"],
                    ["Vojtěch", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Jitka", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Jitka", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Jitka", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Jitka", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Jitka", "Emanuel"],
                    ["Emanuel", "Jitka"],
                    ["Jitka", "Emanuel"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Jitka"],
                    ["Jitka", "rada"],
                    ["rada", "Jitka"],
                    ["Emanuel", "rada"],
                    ["rada", "Emanuel"],
                    ["Otilie", "Emanuel"],
                    ["Emanuel", "Otilie"],
                    ["Václav", "Jitka"],
                    ["Jitka", "Václav"],
                    ["Václav", "Jitka"],
                    ["Jitka", "Václav"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["Gabriela", "Vojtěch"],
                    ["Vojtěch", "Gabriela"],
                    ["Gabriela", "Vojtěch"],
                    ["Vojtěch", "Gabriela"],
                    ["Gabriela", "Vojtěch"],
                    ["Vojtěch", "Gabriela"],
                    ["Gabriela", "Vojtěch"],
                    ["Vojtěch", "Gabriela"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["rada", "Raimund"],
                    ["Raimund", "rada"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Raimund", "Vojtěch"],
                    ["Vojtěch", "Raimund"],
                    ["Jitka", "Raimund"],
                    ["Raimund", "Jitka"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "rada"],
                    ["Jitka", "rada"],
                    ["Gabriela", "rada"],
                    ["rada", "Gabriela"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["Gabriela", "pojezdná"],
                    ["pojezdná", "Gabriela"],
                    ["Gabriela", "Jitka"],
                    ["Jitka", "Gabriela"],
                    ["Gabriela", "Jitka"],
                    ["Jitka", "Gabriela"],
                    ["Gabriela", "Jitka"],
                    ["Jitka", "Gabriela"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],
                    ["Gabriela", "Raimund"],
                    ["Raimund", "Gabriela"],

                ], nodes: 

                    [

                    // hlavní postavy

                    {id: 'Jitka',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Gabriela',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'rada',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Vojtěch',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Emanuel',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Raimund',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Otilie',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'babička',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Kateřina',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'pojezdná',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'Bedřich',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'lékař',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'kněz',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'setník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'páže',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'domovník',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Melichar',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'příbuzní',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'pojezdný',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'šafář',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'mušketýr',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'šafářka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Václav',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'komorná',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
      case "skapulir":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Škapulíř'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["starý pán", "Sychravý"],
                    ["starý pán", "Sychravý"],
                    ["Luisa", "Sychravý"],
                    ["Sychravý", "Luisa"],
                    ["starý pán", "stará paní"],
                    ["stará paní", "starý pán"],
                    ["starý pán", "stará paní"],
                    ["stará paní", "starý pán"],
                    ["starý pán", "stará paní"],
                    ["stará paní", "starý pán"],
                    ["starý pán", "stará paní"],
                    ["stará paní", "starý pán"],
                    ["Kvido", "Sychravý"],
                    ["Sychravý", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["stará paní", "starý pán"],
                    ["starý pán", "stará paní"],
                    ["stará paní", "starý pán"],
                    ["starý pán", "stará paní"],
                    ["stará paní", "starý pán"],
                    ["Kvido", "stará paní"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "stará paní"],
                    ["stará paní", "Kvido"],
                    ["Selena", "stará paní"],
                    ["stará paní", "Selena"],
                    ["Kvido", "Selena"],
                    ["Sychravý", "starý pán"],
                    ["starý pán", "Sychravý"],
                    ["Sychravý", "starý pán"],
                    ["starý pán", "Sychravý"],
                    ["Sychravý", "starý pán"],
                    ["Kvido", "Sychravý"],
                    ["Kvido", "Sychravý"],
                    ["Sychravý", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Kvido"],
                    ["Kvido", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Selena", "Sychravý"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["kníže Lidkov", "Sychravý"],
                    ["Sychravý", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["Sychravý", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["Sychravý", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["Sychravý", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["Sychravý", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["Sychravý", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["starý pán", "kníže Lidkov"],
                    ["kníže Lidkov", "starý pán"],
                    ["Kvido", "starý pán"],
                    ["starý pán", "Kvido"],
                    ["starý pán", "kníže Lidkov"],
                    ["Sychravý", "Selena"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["kníže Lidkov", "Selena"],
                    ["kníže Lidkov", "Sychravý"],
                    ["Sychravý", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Selena"],
                    ["Selena", "kníže Lidkov"],
                    ["kníže Lidkov", "Sychravý"],
                    ["Sychravý", "kníže Lidkov"],
                    ["kníže Lidkov", "Sychravý"],
                    ["Sychravý", "kníže Lidkov"],
                    ["kníže Lidkov", "Sychravý"],
                    ["Sychravý", "kníže Lidkov"],
                    ["kníže Lidkov", "Sychravý"],
                    ["Sychravý", "kníže Lidkov"],
                    ["sousedé", "kozáci"],
                    ["kozáci", "sousedé"],
                    ["starý pán", "Sychravý"],
                    ["Sychravý", "starý pán"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Sychravý", "Selena"],
                    ["starý pán", "Kvido"],
                    ["Kvido", "Sychravý"],
                    ["Sychravý", "Kvido"],
                    ["starý pán", "Sychravý"],
                    ["Kvido", "starý pán"],
                    ["Sychravý", "Kvido"],
                    ["starý pán", "Kvido"],
                    ["Sychravý", "Kvido"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],
                    ["Selena", "Sychravý"],
                    ["Sychravý", "Selena"],

                ], nodes: 

                    [

                    // hlavní postavy

                    {id: 'Selena',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Sychravý',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Kvido',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'kníže Lidkov',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'starý pán',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'stará paní',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'Luisa',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'kozáci',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'sousedé',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
      case "nakosatkach":

      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Na košatkách'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["Matěj", "panímaminka"],
                    ["panímaminka", "Matěj"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["panímaminka", "Serafín"],
                    ["panímaminka", "Augustin"],
                    ["Augustin", "panímaminka"],
                    ["Augustin", "panímaminka"],
                    ["panímaminka", "Augustin"],
                    ["Serafín", "Augustin"],
                    ["Augustin", "Serafín"],
                    ["Augustin", "Serafín"],
                    ["Serafín", "Augustin"],
                    ["panímaminka", "Serafín"],
                    ["Serafín", "panímaminka"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Augustin", "Tomáš"],
                    ["Tomáš", "Augustin"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Augustin", "Tomáš"],
                    ["Tomáš", "Augustin"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Augustin", "Tomáš"],
                    ["Tomáš", "Augustin"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Augustin", "Tomáš"],
                    ["Tomáš", "Augustin"],
                    ["Drozd", "Františka"],
                    ["Františka", "Drozd"],
                    ["panímaminka", "Františka"],
                    ["Tomáš", "Františka"],
                    ["Františka", "Tomáš"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["Drozd", "Františka"],
                    ["Františka", "Drozd"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["panímaminka", "Františka"],
                    ["Františka", "panímaminka"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Matěj", "služka"],
                    ["služka", "Matěj"],
                    ["panímaminka", "Františka"],
                    ["Františka", "panímaminka"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Tomáš", "panímaminka"],
                    ["panímaminka", "Tomáš"],
                    ["Tomáš", "Augustin"],
                    ["Augustin", "Tomáš"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["panímaminka", "Františka"],
                    ["Františka", "panímaminka"],
                    ["hlídač", "Tomáš"],
                    ["Tomáš", "hlídač"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["Tomáš", "Františka"],
                    ["Františka", "Tomáš"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["Tomáš", "Františka"],
                    ["Františka", "Tomáš"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["Tomáš", "Františka"],
                    ["Františka", "Tomáš"],
                    ["Františka", "Tomáš"],
                    ["Tomáš", "Františka"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["Augustin", "Františka"],
                    ["Františka", "Augustin"],
                    ["panímaminka", "Augustin"],
                    ["Augustin", "panímaminka"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["Tomáš", "Serafín"],
                    ["Serafín", "Tomáš"],
                    ["panímaminka", "Tomáš"],
                    ["Tomáš", "panímaminka"],
                    ["panímaminka", "Tomáš"],
                    ["Tomáš", "panímaminka"],
                    ["Tomáš", "Matěj"],
                    ["Matěj", "Tomáš"],

                ], nodes: 

                    [

                    // vypravěč

                    //{id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},

                    // hlavní postavy

                    {id: 'Tomáš',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Františka',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Augustin',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'panímaminka',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Serafín',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'Matěj',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Drozd',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'služka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'hlídač',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
    default:
    document.getElementById("container-person").src = "";   
  }
}






// ŠABLONA:

/*
    case "NÁZEV CASE-TEXTU":
      Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'NÁZEV TEXTU'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
        
                    ["narrator", "JMÉNO POSTAVY"],
                    ...
                    
                ], nodes: 
                    [
                    // vypravěč
                    {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},

                    // hlavní postavy
                    {id: 'NÁZEV POSTAVY 1',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    ...

                    // vedlejší postavy
                    {id: 'NÁZEV POSTAVY 2',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    ...

                    ]
                }
              ]
          });
      break;
*/