function showNetworkGraph() {
  var option = document.getElementById("cluster").value;
  
  const vypravec = '#c4688c',
  postava = '#78a8d1', // postava, se kterou vypravěč nebo jiná postava explicitně komunikuje
  postava2 = '#aeb6bf'; // postava, se kterou vypravěč nebo jiná postava explicitně nekomunikuje, ale komunikace je vyprávěna (např. "promluvil jsem si s X")
  
  const line = '#000000';
  const linewidth = 2.0;

  switch(option){
    case "mistrkampanus":
      Highcharts.chart('container-person', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'Mistr Kampanus'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [

                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Kampanus", "Mollerus"],
                    ["Mollerus", "Kampanus"],
                    ["Mollerus", "Knobelius"],
                    ["Knobelius", "Mollerus"],
                    ["Mollerus", "Knobelius"],
                    ["Knobelius", "Mollerus"],
                    ["Mollerus", "Knobelius"],
                    ["Knobelius", "Mollerus"],
                    ["Mollerus", "Měřínský"],
                    ["Měřínský", "Mollerus"],
                    ["Mollerus", "Měřínský"],
                    ["Měřínský", "Mollerus"],
                    ["Mollerus", "Měřínský"],
                    ["Měřínský", "Mollerus"],
                    ["Knobelius", "Měřínský"],
                    ["Měřínský", "Knobelius"],
                    ["Knobelius", "Měřínský"],
                    ["Měřínský", "Knobelius"],
                    ["Knobelius", "Měřínský"],
                    ["Měřínský", "Knobelius"],
                    ["Knobelius", "Měřínský"],
                    ["Měřínský", "Knobelius"],
                    ["Mollerus", "Vokoun"],
                    ["Vokoun", "Mollerus"],
                    ["Mollerus", "Vokoun"],
                    ["Vokoun", "Mollerus"],
                    ["Mollerus", "Bergerus"],
                    ["Bergerus", "Mollerus"],
                    ["Mollerus", "Bergerus"],
                    ["Bergerus", "Mollerus"],
                    ["Knobelius", "Vokoun"],
                    ["Vokoun", "Knobelius"],
                    ["Mollerus", "Pulpit"],
                    ["Pulpit", "Mollerus"],
                    ["Mollerus", "Pulpit"],
                    ["Pulpit", "Mollerus"],
                    ["Mollerus", "Pulpit"],
                    ["Pulpit", "Mollerus"],
                    ["Mollerus", "Pulpit"],
                    ["Pulpit", "Mollerus"],
                    ["Pulpit", "Knobelius"],
                    ["Knobelius", "Pulpit"],
                    ["Pulpit", "Knobelius"],
                    ["Knobelius", "Pulpit"],
                    ["Mollerus", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Mollerus"],
                    ["Mollerus", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Mollerus"],
                    ["Mollerus", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Mollerus"],
                    ["Měřínský", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Měřínský"],
                    ["Měřínský", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Měřínský"],
                    ["Bergerus", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Bergerus"],
                    ["Kampanus", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Kampanus"],
                    ["Kampanus", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Kampanus"],
                    ["Mollerus", "Jana"],
                    ["Jana", "Mollerus"],
                    ["Knobelius", "Jana"],
                    ["Jana", "Knobelius"],
                    ["Knobelius", "jirchář"],
                    ["jirchář", "Knobelius"],
                    ["Knobelius", "jirchář"],
                    ["jirchář", "Knobelius"],
                    ["Kukla", "jirchář"],
                    ["jirchář", "Kukla"],
                    ["Mollerus", "jirchář"],
                    ["jirchář", "Mollerus"],
                    ["Kukla", "Mollerus"],
                    ["Mollerus", "Kukla"],
                    ["Kukla", "Mollerus"],
                    ["Mollerus", "Kukla"],
                    ["Sixt", "Mollerus"],
                    ["Mollerus", "Sixt"],
                    ["Sixt", "Mollerus"],
                    ["Mollerus", "Sixt"],
                    ["Kukla", "Sixt"],
                    ["Sixt", "Kukla"],
                    ["Třebícký", "Mollerus"],
                    ["Mollerus", "Třebícký"],
                    ["Třebícký", "Mollerus"],
                    ["Mollerus", "Třebícký"],
                    ["Třebícký", "Basilius"],
                    ["Basilius", "Třebícký"],
                    ["Třebícký", "Basilius"],
                    ["Basilius", "Třebícký"],
                    ["Pulpit", "Sixt"],
                    ["Sixt", "Pulpit"],
                    ["Kampanus", "Měřínský"],
                    ["Měřínský", "Kampanus"],
                    ["Kampanus", "Měřínský"],
                    ["Měřínský", "Kampanus"],
                    ["Kampanus", "Měřínský"],
                    ["Měřínský", "Kampanus"],
                    ["Kampanus", "Měřínský"],
                    ["Měřínský", "Kampanus"],
                    ["Kampanus", "Knobelius"],
                    ["Knobelius", "Kampanus"],
                    ["Kampanus", "Knobelius"],
                    ["Knobelius", "Kampanus"],
                    ["Kampanus", "Knobelius"],
                    ["Knobelius", "Kampanus"],
                    ["Kampanus", "Knobelius"],
                    ["Knobelius", "Kampanus"],
                    ["Kampanus", "Knobelius"],
                    ["Knobelius", "Kampanus"],
                    ["Kampanus", "Knobelius"],
                    ["Knobelius", "Kampanus"],
                    ["Kampanus", "Nudožerský"],
                    ["Nudožerský", "Kampanus"],
                    ["Kampanus", "Nudožerský"],
                    ["Nudožerský", "Kampanus"],
                    ["Kampanus", "Nudožerský"],
                    ["Nudožerský", "Kampanus"],
                    ["Kampanus", "Skála"],
                    ["Skála", "Kampanus"],
                    ["Kampanus", "Skála"],
                    ["Skála", "Kampanus"],
                    ["Nudožerský", "Skála"],
                    ["Skála", "Nudožerský"],
                    ["Nudožerský", "Skála"],
                    ["Skála", "Nudožerský"],
                    ["Skála", "Troilus"],
                    ["Troilus", "Skála"],
                    ["Skála", "Troilus"],
                    ["Troilus", "Skála"],
                    ["Troilus", "Nudožerský"],
                    ["Nudožerský", "Troilus"],
                    ["Troilus", "Nudožerský"],
                    ["Nudožerský", "Troilus"],
                    ["Kampanus", "Kochan"],
                    ["Kochan", "Kampanus"],
                    ["Kampanus", "Kochan"],
                    ["Kochan", "Kampanus"],
                    ["Knobelius", "Kochan"],
                    ["Kochan", "Knobelius"],
                    ["Kampanus", "Jičínský"],
                    ["Jičínský", "Kampanus"],
                    ["Kampanus", "Jičínský"],
                    ["Jičínský", "Kampanus"],
                    ["Kampanus", "Jičínský"],
                    ["Jičínský", "Kampanus"],
                    ["Mollerus", "Jičínský"],
                    ["Jičínský", "Mollerus"],
                    ["Mollerus", "Jičínský"],
                    ["Jičínský", "Mollerus"],
                    ["Mollerus", "Jičínský"],
                    ["Jičínský", "Mollerus"],
                    ["Treytlar", "Kampanus"],
                    ["Kampanus", "Treytlar"],
                    ["Marynek", "Kampanus"],
                    ["Kampanus", "Marynek"],
                    ["Kampanus", "Kepler"],
                    ["Kepler", "Kampanus"],
                    ["Kampanus", "Kepler"],
                    ["Kepler", "Kampanus"],
                    ["Kepler", "Budovec"],
                    ["Budovec", "Kepler"],
                    ["Kepler", "Budovec"],
                    ["Budovec", "Kepler"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Troilus"],
                    ["Troilus", "Kampanus"],
                    ["Kampanus", "Budovec"],
                    ["Budovec", "Kampanus"],
                    ["Kampanus", "Budovec"],
                    ["Budovec", "Kampanus"],
                    ["Kampanus", "Budovec"],
                    ["Budovec", "Kampanus"],
                    ["Kampanus", "Budovec"],
                    ["Budovec", "Kampanus"],
                    ["Kampanus", "Budovec"],
                    ["Budovec", "Kampanus"],
                    ["Kampanus", "Thurn"],
                    ["Thurn", "Kampanus"],
                    ["Kampanus", "Thurn"],
                    ["Thurn", "Kampanus"],
                    ["Kampanus", "Thurn"],
                    ["Thurn", "Kampanus"],
                    ["Budovec", "Skála"],
                    ["Skála", "Budovec"],
                    ["Thurn", "Skála"],
                    ["Skála", "Thurn"],
                    ["Borbonius", "Troilus"],
                    ["Troilus", "Borbonius"],
                    ["Borbonius", "Troilus"],
                    ["Troilus", "Borbonius"],
                    ["Kyrchmajer", "Kampanus"],
                    ["Kampanus", "Kyrchmajer"],
                    ["Kyrchmajer", "Kampanus"],
                    ["Kampanus", "Kyrchmajer"],
                    ["Kampanus", "Lidunka"],
                    ["Lidunka", "Kampanus"],
                    ["Kampanus", "Lidunka"],
                    ["Lidunka", "Kampanus"],
                    ["Kampanus", "Lidunka"],
                    ["Lidunka", "Kampanus"],
                    ["Kampanus", "Lidunka"],
                    ["Lidunka", "Kampanus"],
                    ["Lidunka", "Revír"],
                    ["Revír", "Lidunka"],
                    ["Lidunka", "Revír"],
                    ["Revír", "Lidunka"],
                    ["Troilus", "Revír"],
                    ["Revír", "Troilus"],
                    ["Kampanus", "Revír"],
                    ["Revír", "Kampanus"],
                    ["Kampanus", "Revír"],
                    ["Revír", "Kampanus"],
                    ["Kampanus", "Revír"],
                    ["Revír", "Kampanus"],
                    ["Bílek", "Troilus"],
                    ["Troilus", "Bílek"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Mollerus", "Eva"],
                    ["Eva", "Mollerus"],
                    ["Eva", "Michna"],
                    ["Michna", "Eva"],
                    ["Eva", "Michna"],
                    ["Michna", "Eva"],
                    ["Mollerus", "kantor"],
                    ["kantor", "Mollerus"],
                    ["Kampanus", "kantor"],
                    ["kantor", "Kampanus"],
                    ["Kampanus", "Vokoun"],
                    ["Vokoun", "Kampanus"],
                    ["Mollerus", "Tesacius"],
                    ["Tesacius", "Mollerus"],
                    ["Mollerus", "Tesacius"],
                    ["Tesacius", "Mollerus"],
                    ["Borbonius", "Skála"],
                    ["Skála", "Borbonius"],
                    ["Borbonius", "Skála"],
                    ["Skála", "Borbonius"],
                    ["Jessenius", "Budovec"],
                    ["Budovec", "Jessenius"],
                    ["Jessenius", "Budovec"],
                    ["Budovec", "Jessenius"],
                    ["Roupov", "Budovec"],
                    ["Budovec", "Roupov"],
                    ["Roupov", "Budovec"],
                    ["Budovec", "Roupov"],
                    ["Smiřický", "Budovec"],
                    ["Budovec", "Smiřický"],
                    ["Smiřický", "Budovec"],
                    ["Budovec", "Smiřický"],
                    ["Kaplíř", "Budovec"],
                    ["Budovec", "Kaplíř"],
                    ["Kaplíř", "Budovec"],
                    ["Budovec", "Kaplíř"],
                    ["Sixt", "Budovec"],
                    ["Budovec", "Sixt"],
                    ["Sixt", "Budovec"],
                    ["Budovec", "Sixt"],
                    ["Sixt", "Budovec"],
                    ["Budovec", "Sixt"],
                    ["Sušický", "Budovec"],
                    ["Budovec", "Sušický"],
                    ["Sušický", "Budovec"],
                    ["Budovec", "Sušický"],
                    ["Kampanus", "Jessenius"],
                    ["Jessenius", "Kampanus"],
                    ["Kampanus", "Jessenius"],
                    ["Jessenius", "Kampanus"],
                    ["Kampanus", "Jessenius"],
                    ["Jessenius", "Kampanus"],
                    ["Kampanus", "Jessenius"],
                    ["Jessenius", "Kampanus"],
                    ["Kampanus", "Jessenius"],
                    ["Jessenius", "Kampanus"],
                    ["Kampanus", "Jessenius"],
                    ["Jessenius", "Kampanus"],
                    ["Kampanus", "Sixt"],
                    ["Sixt", "Kampanus"],
                    ["Kampanus", "Sixt"],
                    ["Sixt", "Kampanus"],
                    ["Kampanus", "Sixt"],
                    ["Sixt", "Kampanus"],
                    ["Kampanus", "Sixt"],
                    ["Sixt", "Kampanus"],
                    ["Kampanus", "Sixt"],
                    ["Sixt", "Kampanus"],
                    ["Thurn", "Budovec"],
                    ["Budovec", "Thurn"],
                    ["Thurn", "Budovec"],
                    ["Budovec", "Thurn"],
                    ["Thurn", "Budovec"],
                    ["Budovec", "Thurn"],
                    ["Thurn", "Budovec"],
                    ["Budovec", "Thurn"],
                    ["Thurn", "Smiřický"],
                    ["Smiřický", "Thurn"],
                    ["Thurn", "Smiřický"],
                    ["Smiřický", "Thurn"],
                    ["Thurn", "Smiřický"],
                    ["Smiřický", "Thurn"],
                    ["Thurn", "Roupov"],
                    ["Roupov", "Thurn"],
                    ["Thurn", "Roupov"],
                    ["Roupov", "Thurn"],
                    ["Šlik", "Budovec"],
                    ["Budovec", "Šlik"],
                    ["Šlik", "Hošťálek"],
                    ["Hošťálek", "Šlik"],
                    ["Šlik", "Hošťálek"],
                    ["Hošťálek", "Šlik"],
                    ["Thurn", "Martinic"],
                    ["Martinic", "Thurn"],
                    ["Thurn", "Martinic"],
                    ["Martinic", "Thurn"],
                    ["Thurn", "Martinic"],
                    ["Martinic", "Thurn"],
                    ["Thurn", "Slavata"],
                    ["Slavata", "Thurn"],
                    ["Thurn", "Slavata"],
                    ["Slavata", "Thurn"],
                    ["Thurn", "Slavata"],
                    ["Slavata", "Thurn"],
                    ["Šlik", "Martinic"],
                    ["Martinic", "Šlik"],
                    ["Šlik", "Martinic"],
                    ["Martinic", "Šlik"],
                    ["Šlik", "Slavata"],
                    ["Slavata", "Šlik"],
                    ["Šlik", "Slavata"],
                    ["Slavata", "Šlik"],
                    ["Martinic", "Slavata"],
                    ["Slavata", "Martinic"],
                    ["Martinic", "Slavata"],
                    ["Slavata", "Martinic"],
                    ["Martinic", "Slavata"],
                    ["Slavata", "Martinic"],
                    ["Vilém Lobkovic", "Martinic"],
                    ["Martinic", "Vilém Lobkovic"],
                    ["Vilém Lobkovic", "Martinic"],
                    ["Martinic", "Vilém Lobkovic"],
                    ["Smiřický", "Roupov"],
                    ["Roupov", "Smiřický"],
                    ["Smiřický", "Roupov"],
                    ["Roupov", "Smiřický"],
                    ["Sušický", "Roupov"],
                    ["Roupov", "Sušický"],
                    ["Šultys", "Šultys otec"],
                    ["Šultys otec", "Šultys"],
                    ["Šultys", "Šultys otec"],
                    ["Šultys otec", "Šultys"],
                    ["Šultys", "Šultys otec"],
                    ["Šultys otec", "Šultys"],
                    ["Šultys", "Kampanus"],
                    ["Kampanus", "Šultys"],
                    ["Šultys", "Kampanus"],
                    ["Kampanus", "Šultys"],
                    ["Šultys", "Kampanus"],
                    ["Kampanus", "Šultys"],
                    ["Slavata", "Harant"],
                    ["Harant", "Slavata"],
                    ["Slavata", "Harant"],
                    ["Harant", "Slavata"],
                    ["Slavata", "Harant"],
                    ["Harant", "Slavata"],
                    ["Martinic", "Harant"],
                    ["Harant", "Martinic"],
                    ["Martinic", "Harant"],
                    ["Harant", "Martinic"],
                    ["Slavata", "Šternberk"],
                    ["Šternberk", "Slavata"],
                    ["Slavata", "Šternberk"],
                    ["Šternberk", "Slavata"],
                    ["Harant", "Šternberk"],
                    ["Šternberk", "Harant"],
                    ["Harant", "Šternberk"],
                    ["Šternberk", "Harant"],
                    ["Harant", "Polyxena"],
                    ["Polyxena", "Harant"],
                    ["Harant", "Polyxena"],
                    ["Polyxena", "Harant"],
                    ["Polyxena", "Otilie"],
                    ["Otilie", "Polyxena"],
                    ["Polyxena", "Otilie"],
                    ["Otilie", "Polyxena"],
                    ["Harant", "Otilie"],
                    ["Otilie", "Harant"],
                    ["Harant", "Otilie"],
                    ["Otilie", "Harant"],
                    ["Slavata", "arcibiskup"],
                    ["arcibiskup", "Slavata"],
                    ["Slavata", "arcibiskup"],
                    ["arcibiskup", "Slavata"],
                    ["Slavata", "Michna"],
                    ["Michna", "Slavata"],
                    ["Slavata", "Michna"],
                    ["Michna", "Slavata"],
                    ["Slavata", "Michna"],
                    ["Michna", "Slavata"],
                    ["Michna", "Koronius"],
                    ["Koronius", "Michna"],
                    ["Michna", "Koronius"],
                    ["Koronius", "Michna"],
                    ["Michna", "Koronius"],
                    ["Koronius", "Michna"],
                    ["Koronius", "Slavata"],
                    ["Slavata", "Koronius"],
                    ["Mollerus", "Michna"],
                    ["Michna", "Mollerus"],
                    ["Mollerus", "Michna"],
                    ["Michna", "Mollerus"],
                    ["Mollerus", "Michna"],
                    ["Michna", "Mollerus"],
                    ["Mollerus", "Michna"],
                    ["Michna", "Mollerus"],
                    ["Mollerus", "Michna"],
                    ["Michna", "Mollerus"],
                    ["Mollerus", "Slavata"],
                    ["Slavata", "Mollerus"],
                    ["Mollerus", "Slavata"],
                    ["Slavata", "Mollerus"],
                    ["Mollerus", "Slavata"],
                    ["Slavata", "Mollerus"],
                    ["Mollerus", "Basilius"],
                    ["Basilius", "Mollerus"],
                    ["Mollerus", "Basilius"],
                    ["Basilius", "Mollerus"],
                    ["Mollerus", "Basilius"],
                    ["Basilius", "Mollerus"],
                    ["Mollerus", "Pěček"],
                    ["Pěček", "Mollerus"],
                    ["Mollerus", "Pěček"],
                    ["Pěček", "Mollerus"],
                    ["Michna", "Pěček"],
                    ["Pěček", "Michna"],
                    ["Michna", "Pěček"],
                    ["Pěček", "Michna"],
                    ["Michna", "Kapr"],
                    ["Kapr", "Michna"],
                    ["Michna", "Kapr"],
                    ["Kapr", "Michna"],
                    ["Michna", "Přibík"],
                    ["Přibík", "Michna"],
                    ["Michna", "Přibík"],
                    ["Přibík", "Michna"],
                    ["Michna", "Kyrchmajer"],
                    ["Kyrchmajer", "Michna"],
                    ["Michna", "Kyrchmajer"],
                    ["Kyrchmajer", "Michna"],
                    ["Michna", "Celestýn"],
                    ["Celestýn", "Michna"],
                    ["Troilus", "Michna"],
                    ["Michna", "Troilus"],
                    ["Troilus", "Michna"],
                    ["Michna", "Troilus"],
                    ["Troilus", "Michna"],
                    ["Michna", "Troilus"],
                    ["Kapr", "Pěček"],
                    ["Pěček", "Kapr"],
                    ["Jessenius", "Troilus"],
                    ["Troilus", "Jessenius"],
                    ["Jessenius", "Šultys"],
                    ["Šultys", "Jessenius"],
                    ["Mollerus", "Veleslavín"],
                    ["Veleslavín", "Mollerus"],
                    ["Pulpit", "Veleslavín"],
                    ["Veleslavín", "Pulpit"],
                    ["Pulpit", "Veleslavín"],
                    ["Veleslavín", "Pulpit"],
                    ["Thurn", "Hohenlohe"],
                    ["Hohenlohe", "Thurn"],
                    ["Thurn", "Hohenlohe"],
                    ["Hohenlohe", "Thurn"],
                    ["Thurn", "Anhalt"],
                    ["Anhalt", "Thurn"],
                    ["Thurn", "Anhalt"],
                    ["Anhalt", "Thurn"],
                    ["Thurn", "Anhalt"],
                    ["Anhalt", "Thurn"],
                    ["Anhalt", "Hohenlohe"],
                    ["Hohenlohe", "Anhalt"],
                    ["Anhalt", "Hohenlohe"],
                    ["Hohenlohe", "Anhalt"],
                    ["Anhalt", "Kornis"],
                    ["Kornis", "Anhalt"],
                    ["Anhalt", "Kornis"],
                    ["Kornis", "Anhalt"],
                    ["Anhalt", "Materna"],
                    ["Materna", "Anhalt"],
                    ["Veleslavín", "Materna"],
                    ["Materna", "Veleslavín"],
                    ["Veleslavín", "Materna"],
                    ["Materna", "Veleslavín"],
                    ["Veleslavín", "Materna"],
                    ["Materna", "Veleslavín"],
                    ["Veleslavín", "Vostrovec"],
                    ["Vostrovec", "Veleslavín"],
                    ["Veleslavín", "Vostrovec"],
                    ["Vostrovec", "Veleslavín"],
                    ["Veleslavín", "Vostrovec"],
                    ["Vostrovec", "Veleslavín"],
                    ["Veleslavín", "Malovec"],
                    ["Malovec", "Veleslavín"],
                    ["Veleslavín", "Malovec"],
                    ["Malovec", "Veleslavín"],
                    ["Veleslavín", "Knobelius"],
                    ["Knobelius", "Veleslavín"],
                    ["Veleslavín", "Knobelius"],
                    ["Knobelius", "Veleslavín"],
                    ["Vostrovec", "Malovec"],
                    ["Malovec", "Vostrovec"],
                    ["Vostrovec", "Malovec"],
                    ["Malovec", "Vostrovec"],
                    ["Vostrovec", "Hodějovský"],
                    ["Hodějovský", "Vostrovec"],
                    ["Vostrovec", "Hodějovský"],
                    ["Hodějovský", "Vostrovec"],
                    ["Hodějovský", "Anhalt"],
                    ["Anhalt", "Hodějovský"],
                    ["Hodějovský", "Anhalt"],
                    ["Anhalt", "Hodějovský"],
                    ["Kordule", "Veleslavín"],
                    ["Veleslavín", "Kordule"],
                    ["Kordule", "Veleslavín"],
                    ["Veleslavín", "Kordule"],
                    ["Měřínský", "Veleslavín"],
                    ["Veleslavín", "Měřínský"],
                    ["Fridrich", "Roupov"],
                    ["Roupov", "Fridrich"],
                    ["Fridrich", "Roupov"],
                    ["Roupov", "Fridrich"],
                    ["Fridrich", "Cyril"],
                    ["Cyril", "Fridrich"],
                    ["Fridrich", "Cyril"],
                    ["Cyril", "Fridrich"],
                    ["Fridrich", "Dikast"],
                    ["Dikast", "Fridrich"],
                    ["Fridrich", "Dikast"],
                    ["Dikast", "Fridrich"],
                    ["Fridrich", "Jessenius"],
                    ["Jessenius", "Fridrich"],
                    ["Fridrich", "Jessenius"],
                    ["Jessenius", "Fridrich"],
                    ["Fridrich", "Kampanus"],
                    ["Kampanus", "Fridrich"],
                    ["Kampanus", "Descartes"],
                    ["Descartes", "Kampanus"],
                    ["Kampanus", "Descartes"],
                    ["Descartes", "Kampanus"],
                    ["Kampanus", "Descartes"],
                    ["Descartes", "Kampanus"],
                    ["Kampanus", "Descartes"],
                    ["Descartes", "Kampanus"],
                    ["Kampanus", "Descartes"],
                    ["Descartes", "Kampanus"],
                    ["Descartes", "Koňasová"],
                    ["Koňasová", "Descartes"],
                    ["Kampanus", "Pulpit"],
                    ["Pulpit", "Kampanus"],
                    ["Kampanus", "Pulpit"],
                    ["Pulpit", "Kampanus"],
                    ["Kampanus", "Pulpit"],
                    ["Pulpit", "Kampanus"],
                    ["Kampanus", "jirchář"],
                    ["jirchář", "Kampanus"],
                    ["Kampanus", "Koňasová"],
                    ["Koňasová", "Kampanus"],
                    ["Kampanus", "Borbonius"],
                    ["Borbonius", "Kampanus"],
                    ["Kampanus", "Borbonius"],
                    ["Borbonius", "Kampanus"],
                    ["Kampanus", "Borbonius"],
                    ["Borbonius", "Kampanus"],
                    ["Kampanus", "Borbonius"],
                    ["Borbonius", "Kampanus"],
                    ["Kampanus", "Michna"],
                    ["Michna", "Kampanus"],
                    ["Kampanus", "Michna"],
                    ["Michna", "Kampanus"],
                    ["Kampanus", "Michna"],
                    ["Michna", "Kampanus"],
                    ["Kampanus", "Michna"],
                    ["Michna", "Kampanus"],
                    ["Kampanus", "Michna"],
                    ["Michna", "Kampanus"],
                    ["Kampanus", "Michna"],
                    ["Michna", "Kampanus"],
                    ["Kampanus", "Lichtenštejn"],
                    ["Lichtenštejn", "Kampanus"],
                    ["Kampanus", "Lichtenštejn"],
                    ["Lichtenštejn", "Kampanus"],
                    ["Kampanus", "Lichtenštejn"],
                    ["Lichtenštejn", "Kampanus"],
                    ["Kampanus", "Sixtová"],
                    ["Sixtová", "Kampanus"],
                    ["Kampanus", "Sixtová"],
                    ["Sixtová", "Kampanus"],
                    ["Kampanus", "Sixtová"],
                    ["Sixtová", "Kampanus"],
                    ["Sixt", "Sixtová"],
                    ["Sixtová", "Sixt"],
                    ["Kampanus", "Kaplíř"],
                    ["Kaplíř", "Kampanus"],
                    ["Kampanus", "Kaplíř"],
                    ["Kaplíř", "Kampanus"],
                    ["Kampanus", "Kaplíř"],
                    ["Kaplíř", "Kampanus"],
                    ["Kampanus", "Otta z Lozu"],
                    ["Otta z Lozu", "Kampanus"],
                    ["Kampanus", "Otta z Lozu"],
                    ["Otta z Lozu", "Kampanus"],
                    ["Kampanus", "Harant"],
                    ["Harant", "Kampanus"],
                    ["Kampanus", "Harant"],
                    ["Harant", "Kampanus"],
                    ["Kampanus", "Hošťálek"],
                    ["Hošťálek", "Kampanus"],
                    ["Kampanus", "Sušický"],
                    ["Sušický", "Kampanus"],
                    ["Vrbenský", "Kampanus"],
                    ["Kampanus", "Vrbenský"],
                    ["Vrbenský", "Kampanus"],
                    ["Kampanus", "Vrbenský"],
                    ["Vrbenský", "Kampanus"],
                    ["Kampanus", "Vrbenský"],
                    ["Vrbenský", "Sušický"],
                    ["Sušický", "Vrbenský"],
                    ["Vrbenský", "Kochan"],
                    ["Kochan", "Vrbenský"],
                    ["Rosacius", "Kaplíř"],
                    ["Kaplíř", "Rosacius"],
                    ["Rosacius", "Otta z Lozu"],
                    ["Otta z Lozu", "Rosacius"],
                    ["Budovec", "Šlik"],
                    ["Šlik", "Budovec"],
                    ["Harant", "Budovec"],
                    ["Budovec", "Harant"],
                    ["Kochan", "paní Kochanová"],
                    ["paní Kochanová", "Kochan"],
                    ["Kampanus", "paní Kochanová"],
                    ["paní Kochanová", "Kampanus"],
                    ["Kampanus", "Andreae"],
                    ["Andreae", "Kampanus"],
                    ["Kampanus", "Lev z Levengrünu"],
                    ["Lev z Levengrünu", "Kampanus"],
                    ["Kampanus", "Jan z Trnice"],
                    ["Jan z Trnice", "Kampanus"],
                    ["Kapr", "Troilus"],
                    ["Troilus", "Kapr"],
                    ["Kampanus", "Kapr"],
                    ["Kapr", "Kampanus"],
                    ["Kampanus", "Basilius"],
                    ["Basilius", "Kampanus"],
                    ["Kampanus", "Basilius"],
                    ["Basilius", "Kampanus"],
                    ["Kampanus", "Basilius"],
                    ["Basilius", "Kampanus"],
                    ["Basilius", "Mollerus"],
                    ["Mollerus", "Basilius"],
                    ["Basilius", "Mollerus"],
                    ["Mollerus", "Basilius"],
                    ["Basilius", "Michna"],
                    ["Michna", "Basilius"],
                    ["Basilius", "Michna"],
                    ["Michna", "Basilius"],
                    ["Kampanus", "Koronius"],
                    ["Koronius", "Kampanus"],
                    ["Kampanus", "Koronius"],
                    ["Koronius", "Kampanus"],
                    ["Kampanus", "Koronius"],
                    ["Koronius", "Kampanus"],
                    ["Kampanus", "Koronius"],
                    ["Koronius", "Kampanus"],
                    ["Kampanus", "Cyril"],
                    ["Cyril", "Kampanus"],
                    ["Kampanus", "Cyril"],
                    ["Cyril", "Kampanus"],
                    ["Kampanus", "Kateřina Kaménková"],
                    ["Kateřina Kaménková", "Kampanus"],
                    ["Roupov", "Berka"],
                    ["Berka", "Roupov"],
                    ["Budovec", "Berka"],
                    ["Berka", "Budovec"],

                    ], nodes: 

                    [

                    // hlavní postavy

                    {id: 'Kampanus',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Mollerus',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Knobelius',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Měřínský',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Eva',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Troilus',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Budovec',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Thurn',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Michna',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Jessenius',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Slavata',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Sixt',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Šultys',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    {id: 'Lichtenštejn',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},

                    // vedlejší postavy

                    {id: 'Vokoun',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Bergerus',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Pulpit',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kateřina Kaménková',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Jana',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'jirchář',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kukla',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Třebícký',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Basilius',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Nudožerský',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Skála',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kochan',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Jičínský',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Treytlar',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Marynek',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kepler',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Borbonius',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kyrchmajer',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Lidunka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Revír',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Bílek',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'kantor',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Tesacius',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Roupov',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Smiřický',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kaplíř',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Sušický',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Šlik',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Hošťálek',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Martinic',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Vilém Lobkovic',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Šultys otec',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Harant',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Šternberk',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Polyxena',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Otilie',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'arcibiskup',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Koronius',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Pěček',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kapr',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Přibík',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Celestýn',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Veleslavín',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Hohenlohe',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Anhalt',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kornis',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Materna',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Vostrovec',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Malovec',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Hodějovský',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Kordule',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Fridrich',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Cyril',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Dikast',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Descartes',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Koňasová',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Sixtová',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Otta z Lozu',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Vrbenský',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Rosacius',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'paní Kochanová',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Andreae',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Lev z Levengrünu',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Jan z Trnice',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    {id: 'Berka',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},

                    ]

                    }

              ]

          });

      document.getElementById("legend").innerHTML = '<b>Legend:</b> <span style="color:' + vypravec + '">&#9679;</span> narrator, <span style="color:' + postava + '">&#9679;</span> main characters, <span style="color:' + postava2 + '">&#9679;</span> minor characters';
      break;
    default:
    document.getElementById("container-person").src = "";   
  }
}






// ŠABLONA:

/*
    case "NÁZEV CASE-TEXTU":
      Highcharts.chart('container', {chart: {type: 'networkgraph',marginTop: 80},title: {text: 'NÁZEV TEXTU'}, tooltip: {formatter: function () {let info; switch (this.color) { case vypravec: console.log(vypravec); info = " - homodiegetic"; break; case postava: console.log(postava); info = " - character"; break; case postava2: console.log(postava2); info = " - character"; break;} return '<b>' + this.key + '</b> ' + info; }}, plotOptions: {networkgraph: {keys: ['from', 'to'], layoutAlgorithm: {gravitationalConstant: 0.0625, enableSimulation: true, integration: 'verlet', linkLength: 200}}},  series: [{link: {width: 1.5, dashStyle: 'solid'}, marker: {radius: 13 }, dataLabels: {enabled: true, linkFormat: '', allowOverlap: true, style: {textOutline: false}}, data: [
        
                    ["narrator", "JMÉNO POSTAVY"],
                    ...
                    
                ], nodes: 
                    [
                    // vypravěč
                    {id: 'narrator', marker: {radius: 30, lineWidth: linewidth, lineColor: line}, color: vypravec},

                    // hlavní postavy
                    {id: 'NÁZEV POSTAVY 1',marker: {radius: 20,lineWidth: linewidth, lineColor: line}, color: postava},
                    ...

                    // vedlejší postavy
                    {id: 'NÁZEV POSTAVY 2',marker: {radius: 10, lineWidth: linewidth, lineColor: line}, color: postava2},
                    ...

                    ]
                }
              ]
          });
      break;
*/